using Daggerfall.Import.Normalized;

namespace Daggerfall.Import.Normalization;

/// <summary>Purpose-neutral media families used by normalized content packs.</summary>
public enum NormalizedMediaKind
{
    Texture,
    Billboard,
    EnemySprite,
    WeaponSprite,
    EffectSprite,
    Audio,
    UserInterface,
    Font,
}

/// <summary>
/// A generated media artifact. Derived artifact bytes, dimensions, path, and
/// hash are supplied by the importer. An authored overlay may select a bounded
/// display rectangle for a generated frame without changing those bytes.
/// </summary>
public sealed record GeneratedMediaArtifact(
    string Id,
    NormalizedMediaKind Kind,
    string RelativePath,
    byte[] Bytes,
    int SourceWidth,
    int SourceHeight,
    NormalizedSpriteAtlas? Atlas = null,
    string MimeType = "application/octet-stream")
{
    internal void Validate()
    {
        NormalizedImportDocument.RequireLogicalId(Id, nameof(Id));
        NormalizedImportDocument.RequireLogicalPath(RelativePath, nameof(RelativePath));
        if (!Enum.IsDefined(Kind) || Bytes is null || Bytes.Length == 0 || string.IsNullOrWhiteSpace(MimeType))
        {
            throw new ArgumentException("A generated media artifact requires a known kind, bytes, and MIME type.");
        }

        if (SourceWidth < 0 || SourceHeight < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(SourceWidth), "Source dimensions cannot be negative.");
        }

        if (Atlas is not null && (SourceWidth == 0 || SourceHeight == 0))
        {
            throw new InvalidOperationException("Sprite artifacts require regenerated source dimensions.");
        }

        if (Atlas is not null && (!Bytes.AsSpan().SequenceEqual(Atlas.PngBytes) || ContentDigest.Compute(Bytes) != Atlas.PngDigest))
        {
            throw new InvalidOperationException("A sprite artifact must publish the bytes and digest regenerated by its atlas.");
        }
    }

    /// <summary>Creates a sprite artifact from its regenerated atlas, never an old manifest layout.</summary>
    public static GeneratedMediaArtifact FromAtlas(string id, NormalizedMediaKind kind, string relativePath, NormalizedSpriteAtlas atlas)
    {
        ArgumentNullException.ThrowIfNull(atlas);
        int sourceWidth = atlas.Frames.Max(frame => frame.SourceWidth);
        int sourceHeight = atlas.Frames.Max(frame => frame.SourceHeight);
        return new(id, kind, relativePath, atlas.PngBytes.ToArray(), sourceWidth, sourceHeight, atlas, "image/png");
    }
}

/// <summary>
/// Narrow typed authored values. Callers cannot pass a previous raw manifest,
/// so generated bytes and artifact identity cannot accidentally be retained
/// across import.
/// </summary>
public sealed record AuthoredMediaFrameRect(int FrameIndex, int X, int Y, int Width, int Height)
{
    internal void Validate()
    {
        if (FrameIndex < 0 || X < 0 || Y < 0 || Width <= 0 || Height <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(FrameIndex), "An authored frame rectangle requires a non-negative frame and origin and positive dimensions.");
        }
    }
}

/// <summary>Optional playback timing for one named source state.</summary>
public sealed record AuthoredMediaStateTiming(string Name, float? FramesPerSecond = null, bool? Loop = null);

/// <summary>Optional playback timing for one named source action.</summary>
public sealed record AuthoredMediaActionTiming(string Name, float? FramesPerSecond = null, bool? Loop = null);

public sealed record AuthoredMediaOverlay(
    string Id,
    bool IsAuthored,
    string? DisplayName = null,
    NormalizedVector2? Pivot = null,
    NormalizedVector2? DisplaySize = null,
    float? FramesPerSecond = null,
    bool? Loop = null,
    IReadOnlyList<int>? Sequence = null,
    IReadOnlyList<AuthoredMediaFrameRect>? FrameRects = null,
    IReadOnlyList<AuthoredMediaStateTiming>? StateTimings = null,
    IReadOnlyList<AuthoredMediaActionTiming>? ActionTimings = null)
{
    internal void Validate(GeneratedMediaArtifact artifact)
    {
        int frameCount = artifact.Atlas?.Frames.Count ?? 0;
        NormalizedImportDocument.RequireLogicalId(Id, nameof(Id));
        if (!IsAuthored && (DisplayName is not null || Pivot is not null || DisplaySize is not null || FramesPerSecond is not null || Loop is not null || Sequence is not null
            || FrameRects is not null || StateTimings is not null || ActionTimings is not null))
        {
            throw new InvalidOperationException("Only explicitly authored overlays may carry tunable values.");
        }

        if (DisplayName is not null && (string.IsNullOrWhiteSpace(DisplayName) || DisplayName.Any(char.IsControl)))
        {
            throw new ArgumentException("A display name must be non-empty plain text.", nameof(DisplayName));
        }

        Pivot?.Validate(nameof(Pivot));
        DisplaySize?.Validate(nameof(DisplaySize));
        if (DisplaySize is { X: <= 0F } or { Y: <= 0F })
        {
            throw new ArgumentOutOfRangeException(nameof(DisplaySize), "An authored display size must be positive.");
        }

        if (FramesPerSecond is <= 0F || (FramesPerSecond is not null && !float.IsFinite(FramesPerSecond.Value)))
        {
            throw new ArgumentOutOfRangeException(nameof(FramesPerSecond), "An authored frame rate must be finite and positive.");
        }

        if (Sequence is not null)
        {
            if (frameCount == 0 || Sequence.Count == 0 || Sequence.Any(index => index < 0 || index >= frameCount))
            {
                throw new ArgumentException("An authored frame sequence must refer to regenerated frames.", nameof(Sequence));
            }
        }

        ValidateFrameRects(artifact);
        ValidateTimings(StateTimings, nameof(StateTimings));
        ValidateTimings(ActionTimings, nameof(ActionTimings));
    }

    private void ValidateFrameRects(GeneratedMediaArtifact artifact)
    {
        if (FrameRects is null) return;
        if (artifact.Atlas is null)
        {
            throw new ArgumentException("An authored frame rectangle requires a regenerated sprite atlas.", nameof(FrameRects));
        }

        HashSet<int> indexes = [];
        foreach (AuthoredMediaFrameRect rect in FrameRects)
        {
            ArgumentNullException.ThrowIfNull(rect);
            rect.Validate();
            if (!indexes.Add(rect.FrameIndex) || !artifact.Atlas.Frames.Any(frame => frame.FrameIndex == rect.FrameIndex)
                || rect.X > artifact.Atlas.Width - rect.Width || rect.Y > artifact.Atlas.Height - rect.Height)
            {
                throw new ArgumentException("An authored frame rectangle must uniquely identify and remain inside a regenerated atlas frame.", nameof(FrameRects));
            }
        }
    }

    private static void ValidateTimings<TTiming>(IReadOnlyList<TTiming>? timings, string parameterName)
        where TTiming : class
    {
        if (timings is null) return;
        HashSet<string> names = new(StringComparer.Ordinal);
        foreach (TTiming timing in timings)
        {
            ArgumentNullException.ThrowIfNull(timing);
            string name = timing switch
            {
                AuthoredMediaStateTiming state => state.Name,
                AuthoredMediaActionTiming action => action.Name,
                _ => throw new InvalidOperationException("Unknown authored timing type."),
            };
            float? framesPerSecond = timing switch
            {
                AuthoredMediaStateTiming state => state.FramesPerSecond,
                AuthoredMediaActionTiming action => action.FramesPerSecond,
                _ => null,
            };
            bool? loop = timing switch
            {
                AuthoredMediaStateTiming state => state.Loop,
                AuthoredMediaActionTiming action => action.Loop,
                _ => null,
            };
            if (string.IsNullOrWhiteSpace(name) || name.Any(char.IsControl) || !names.Add(name)
                || (framesPerSecond is null && loop is null) || framesPerSecond is <= 0F || (framesPerSecond is not null && !float.IsFinite(framesPerSecond.Value)))
            {
                throw new ArgumentException("An authored timing must uniquely identify a named playback with a finite positive frame rate or loop value.", parameterName);
            }
        }
    }
}

/// <summary>Content-addressed media artifact with regenerated physical facts and narrow authored metadata.</summary>
public sealed record NormalizedMediaDescriptor(
    string Id,
    NormalizedMediaKind Kind,
    string RelativePath,
    ContentDigest ContentDigest,
    long ByteLength,
    string MimeType,
    int SourceWidth,
    int SourceHeight,
    int AtlasWidth,
    int AtlasHeight,
    IReadOnlyList<NormalizedAtlasFrame> Frames,
    string? DisplayName,
    NormalizedVector2? Pivot,
    NormalizedVector2? DisplaySize,
    float? FramesPerSecond,
    bool? Loop,
    IReadOnlyList<int>? Sequence,
    IReadOnlyList<NormalizedAtlasFrame>? GeneratedFrames = null)
{
    public NormalizedArtifactDescriptor ToArtifactDescriptor() => new(
        NormalizedArtifactDescriptor.CurrentSchemaVersion,
        $"artifact/{Id}",
        RelativePath,
        ContentDigest,
        ByteLength,
        []);
}

/// <summary>Stable closure of normalized media descriptors, ordered solely by logical ID.</summary>
public sealed record NormalizedMediaManifest(IReadOnlyList<NormalizedMediaDescriptor> Resources)
{
    public IReadOnlyList<NormalizedArtifactDescriptor> ToArtifactDescriptors() =>
        Resources.Select(resource => resource.ToArtifactDescriptor()).ToArray();
}

public static class MediaManifestNormalizer
{
    public static NormalizedMediaManifest Normalize(
        IEnumerable<GeneratedMediaArtifact> generatedArtifacts,
        IEnumerable<AuthoredMediaOverlay>? overlays = null,
        long maximumArtifactBytes = 16L * 1024 * 1024)
    {
        ArgumentNullException.ThrowIfNull(generatedArtifacts);
        if (maximumArtifactBytes <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(maximumArtifactBytes));
        }

        Dictionary<string, AuthoredMediaOverlay> overlaysById = BuildOverlayIndex(overlays);
        List<GeneratedMediaArtifact> generated = generatedArtifacts.OrderBy(artifact => artifact.Id, StringComparer.Ordinal).ToList();
        if (generated.Count == 0)
        {
            throw new ArgumentException("A media manifest requires at least one artifact.", nameof(generatedArtifacts));
        }

        if (generated.Select(artifact => artifact.Id).Distinct(StringComparer.Ordinal).Count() != generated.Count
            || generated.Select(artifact => artifact.RelativePath).Distinct(StringComparer.Ordinal).Count() != generated.Count)
        {
            throw new InvalidOperationException("Media artifact IDs and logical paths must be unique.");
        }

        List<NormalizedMediaDescriptor> resources = new(generated.Count);
        foreach (GeneratedMediaArtifact artifact in generated)
        {
            artifact.Validate();
            if (artifact.Bytes.LongLength > maximumArtifactBytes)
            {
                throw new InvalidOperationException($"Media artifact '{artifact.Id}' exceeds the encoded byte quota.");
            }

            AuthoredMediaOverlay? overlay = overlaysById.GetValueOrDefault(artifact.Id);
            overlay?.Validate(artifact);
            resources.Add(new(
                artifact.Id,
                artifact.Kind,
                artifact.RelativePath,
                ContentDigest.Compute(artifact.Bytes),
                artifact.Bytes.LongLength,
                artifact.MimeType,
                artifact.SourceWidth,
                artifact.SourceHeight,
                artifact.Atlas?.Width ?? 0,
                artifact.Atlas?.Height ?? 0,
                ApplyFrameRects(artifact.Atlas?.Frames, overlay?.FrameRects),
                overlay?.DisplayName,
                overlay?.Pivot,
                overlay?.DisplaySize,
                overlay?.FramesPerSecond,
                overlay?.Loop,
                overlay?.Sequence?.ToArray(),
                artifact.Atlas?.Frames.OrderBy(frame => frame.FrameIndex).ThenBy(frame => frame.Id, StringComparer.Ordinal).ToArray()));
        }

        if (overlaysById.Keys.Except(resources.Select(resource => resource.Id), StringComparer.Ordinal).Any())
        {
            throw new InvalidOperationException("An authored overlay must identify a generated media artifact.");
        }

        return new(resources);
    }

    private static IReadOnlyList<NormalizedAtlasFrame> ApplyFrameRects(IReadOnlyList<NormalizedAtlasFrame>? frames, IReadOnlyList<AuthoredMediaFrameRect>? rectangles) =>
        frames is null ? [] : frames.OrderBy(frame => frame.FrameIndex).ThenBy(frame => frame.Id, StringComparer.Ordinal).Select(frame =>
        {
            AuthoredMediaFrameRect? rect = rectangles?.SingleOrDefault(value => value.FrameIndex == frame.FrameIndex);
            return rect is null ? frame : frame with { X = rect.X, Y = rect.Y, Width = rect.Width, Height = rect.Height };
        }).ToArray();

    private static Dictionary<string, AuthoredMediaOverlay> BuildOverlayIndex(IEnumerable<AuthoredMediaOverlay>? overlays)
    {
        Dictionary<string, AuthoredMediaOverlay> result = new(StringComparer.Ordinal);
        if (overlays is null) return result;
        foreach (AuthoredMediaOverlay overlay in overlays)
        {
            ArgumentNullException.ThrowIfNull(overlay);
            if (!result.TryAdd(overlay.Id, overlay))
            {
                throw new InvalidOperationException($"Multiple authored overlays identify '{overlay.Id}'.");
            }
        }

        return result;
    }
}
