using Rusty.Engine;
using static WorldRpg.Rulesets.Daggerfall.Tests.TestSessions;

namespace WorldRpg.Rulesets.Daggerfall.Tests;

internal sealed class ContentFake : IContentService
{

    public void PackContainer(ContentContainerPackRequest request) =>
        throw new NotSupportedException("This fake does not pack installed content containers.");

    public ContentBundle OpenContainer(ContentContainerOpenRequest request) =>
        throw new NotSupportedException("This fake does not admit installed content containers.");
    public ContentSha256 ReadBundleIdentity(ContentBundle bundle) =>
        throw new NotSupportedException("This fake does not model container identities.");

    public PortableAsset LoadPortableAsset(PortableAssetLoadRequest request) => throw new NotSupportedException();
    public PortableAssetReadoutResult ReadPortableAsset(PortableAsset asset) => throw new NotSupportedException();
    public ContentReference OpenPortableAssetMember(PortableAssetMemberRequest request) => throw new NotSupportedException();
    // The pinned pair grew a bundle surface. Nothing in this product opens a bundle yet - content is
    // admitted as one snapshot - so the fake refuses these rather than pretending a bundle exists:
    // a test double that answered with an empty bundle would hide a caller that started using one.
    public ContentReference AdmitReference(ContentAdmissionRequest request)
    {
        // Admitting generated bytes registers them under their path exactly as an opened file is, so a
        // read of the returned reference answers the bytes that were admitted.
        byte[] body = request.Bytes.ToArray();
        Add(request.Path, Digest(body), body);
        return ResolveReference(new ContentResolveRequest(request.Path, values[request.Path]));
    }

    public ReadOnlyMemory<ContentBundleInfo> ListBundles() =>
        throw new NotSupportedException("This fake admits one content snapshot and carries no bundles.");

    public ContentBundle OpenBundle(ContentBundleOpenRequest request) =>
        throw new NotSupportedException($"This fake admits one content snapshot, so bundle '{request}' cannot be opened.");

    public ReadOnlyMemory<ContentReferenceInfo> ReadBundleFiles(ContentBundle bundle) =>
        throw new NotSupportedException("This fake admits one content snapshot and carries no bundle files.");

    public ContentReference OpenBundleReference(ContentBundleReferenceRequest request) =>
        throw new NotSupportedException($"This fake admits one content snapshot, so bundle reference '{request}' cannot be opened.");

    private readonly List<string> releases;
    private readonly Dictionary<string, ContentSha256> values = new(StringComparer.Ordinal);
    private readonly Dictionary<string, byte[]> bodies = new(StringComparer.Ordinal);
    private readonly Dictionary<string, int> reads = new(StringComparer.Ordinal);
    private readonly Dictionary<ulong, KeyValuePair<string, ContentSha256>> references = [];
    private ulong nextHandle = 1;

    internal ContentFake(string path, ContentSha256 hash, List<string> releaseLog) : this(releaseLog) => Add(path, hash);
    internal ContentFake(List<string> releaseLog) => releases = releaseLog;

    internal void Add(string contentPath, ContentSha256 contentHash) => values[contentPath] = contentHash;

    /// <summary>Admits one file with the bytes an admitted read returns for it.</summary>
    internal void Add(string contentPath, byte[] body) => Add(contentPath, Digest(body), body);

    internal void Add(string contentPath, ContentSha256 contentHash, byte[] body)
    {
        values[contentPath] = contentHash;
        bodies[contentPath] = body;
    }

    public ContentReference OpenReference(ContentOpenRequest request) => ResolveReference(new ContentResolveRequest(request.Path, values[request.Path]));

    public ContentReference ResolveReference(ContentResolveRequest request)
    {
        ResolveCalls++;
        if (!values.TryGetValue(request.Path, out ContentSha256 known) || known != request.Sha256) throw new InvalidOperationException("Unexpected content reference.");
        ulong value = nextHandle++;
        references.Add(value, new KeyValuePair<string, ContentSha256>(request.Path, known));
        return new ContentReference(new ContentReferenceHandle(value), () => releases.Add("content"));
    }

    /// <summary>How many admitted reads this fake served for one path, which shows how it was chunked.</summary>
    internal int Reads(string path) => reads.GetValueOrDefault(path);

    public ReadOnlyMemory<ContentReferenceInfo> ReadReferenceInfo(ContentReference reference)
    {
        KeyValuePair<string, ContentSha256> item = references[reference.Handle.Value];
        ulong length = bodies.TryGetValue(item.Key, out byte[]? body) ? (ulong)body.Length : 1;
        return new[] { new ContentReferenceInfo(item.Key, item.Value, length) };
    }

    public ReadOnlyMemory<byte> ReadBytes(ContentReadBytesRequest request)
    {
        string path = references[request.Reference.Handle.Value].Key;
        // The Engine serves at most one mebibyte per admitted read, so this fake does too: a fake
        // that answered a larger request would hide a reader that asked for a whole artifact.
        if (request.MaxBytes > 1024 * 1024) throw new InvalidOperationException($"Admitted content reads are bounded to one mebibyte, not {request.MaxBytes}.");
        reads[path] = reads.GetValueOrDefault(path) + 1;
        if (!bodies.TryGetValue(path, out byte[]? body)) return ReadOnlyMemory<byte>.Empty;
        if (request.Offset > (ulong)body.Length) throw new InvalidOperationException($"Read of '{path}' starts past its admitted bytes.");
        int available = checked((int)Math.Min(request.MaxBytes, (ulong)body.Length - request.Offset));
        return body.AsMemory(checked((int)request.Offset), available);
    }
    internal int ResolveCalls { get; private set; }
}
/// <summary>Build-declared bundles for full-product tests; bodies stay outside the eager snapshot.</summary>
/// <remarks>
/// A file is either held in memory or read from the checkout when first used, as the Engine reads a staged
/// bundle file; a disk-backed file's digest is measured once per test run. While a bundle is open its files
/// also resolve by their content path (its root and bundle path), as the Engine resolves a retained reference.
/// </remarks>
internal sealed class BundleContentFake : IContentService
{
    private static readonly System.Collections.Concurrent.ConcurrentDictionary<string, (ContentSha256 Digest, ulong Length)> DiskDigests = new(StringComparer.Ordinal);

    public void PackContainer(ContentContainerPackRequest request) =>
        throw new NotSupportedException("This fake does not pack installed content containers.");

    public ContentBundle OpenContainer(ContentContainerOpenRequest request) =>
        throw new NotSupportedException("This fake does not admit installed content containers.");
    public ContentSha256 ReadBundleIdentity(ContentBundle bundle)
    {
        // Identity reflects the fake's admitted entries; it is not a container-format test.
        string entries = string.Join("\n", ReadBundleFiles(bundle).Span.ToArray()
            .Select(entry => $"{entry.Path}:{entry.Sha256}:{entry.ByteLength}"));
        return Digest(System.Text.Encoding.UTF8.GetBytes(entries));
    }

    public PortableAsset LoadPortableAsset(PortableAssetLoadRequest request) => throw new NotSupportedException();
    public PortableAssetReadoutResult ReadPortableAsset(PortableAsset asset) => throw new NotSupportedException();
    public ContentReference OpenPortableAssetMember(PortableAssetMemberRequest request) => throw new NotSupportedException();

    private sealed class BundleFile(byte[]? bytes, string? diskPath)
    {
        internal byte[] Read() => bytes ?? TestContentFiles.ReadUncached(diskPath!);

        internal (ContentSha256 Digest, ulong Length) Identity() => bytes is not null
            ? (Digest(bytes), checked((ulong)bytes.Length))
            : DiskDigests.GetOrAdd(diskPath!, path =>
            {
                using FileStream stream = File.OpenRead(path);
                byte[] hash = System.Security.Cryptography.SHA256.HashData(stream);
                return (new ContentSha256(
                    System.Buffers.Binary.BinaryPrimitives.ReadUInt64BigEndian(hash.AsSpan(0, 8)),
                    System.Buffers.Binary.BinaryPrimitives.ReadUInt64BigEndian(hash.AsSpan(8, 8)),
                    System.Buffers.Binary.BinaryPrimitives.ReadUInt64BigEndian(hash.AsSpan(16, 8)),
                    System.Buffers.Binary.BinaryPrimitives.ReadUInt64BigEndian(hash.AsSpan(24, 8))), checked((ulong)stream.Length));
            });
    }

    private readonly Dictionary<string, Dictionary<string, BundleFile>> files = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> roots = new(StringComparer.Ordinal);
    private readonly Dictionary<ulong, string> openedBundles = [];
    private readonly Dictionary<ulong, (string Bundle, string Path)> references = [];
    private ulong nextHandle = 1;

    /// <summary>Every bundle file the product opened, in order, as its bundle and its path inside it.</summary>
    internal List<(string Bundle, string Path)> OpenedReferences { get; } = [];

    /// <summary>Every bundle the product opened, in order.</summary>
    internal List<string> OpenedBundles { get; } = [];

    /// <summary>Every bundle file whose body the product read, in order.</summary>
    internal List<(string Bundle, string Path)> ReadFiles { get; } = [];

    internal void Add(string bundle, string path, byte[] bytes) => Files(bundle).Add(path, new(bytes, null));

    /// <summary>Declares a bundle file read from the checkout only when the product uses it.</summary>
    internal void AddFile(string bundle, string path, string diskPath) => Files(bundle).Add(path, new(null, diskPath));

    /// <summary>Names the content root a declared bundle's files resolve under while it is open.</summary>
    internal void Root(string bundle, string root) => roots[bundle] = root;

    private Dictionary<string, BundleFile> Files(string bundle)
    {
        if (!files.TryGetValue(bundle, out Dictionary<string, BundleFile>? values)) files.Add(bundle, values = new(StringComparer.Ordinal));
        return values;
    }

    public ReadOnlyMemory<ContentBundleInfo> ListBundles() => files
        .OrderBy(entry => entry.Key, StringComparer.Ordinal)
        .Select(entry => new ContentBundleInfo(entry.Key, checked((ulong)entry.Value.Count), 0))
        .ToArray();

    public ContentBundle OpenBundle(ContentBundleOpenRequest request)
    {
        if (!files.ContainsKey(request.Id)) throw new FileNotFoundException("Test bundle is not declared.", request.Id);
        ulong handle = nextHandle++;
        openedBundles.Add(handle, request.Id);
        OpenedBundles.Add(request.Id);
        return new(new ContentBundleHandle(handle), () => openedBundles.Remove(handle));
    }

    public ReadOnlyMemory<ContentReferenceInfo> ReadBundleFiles(ContentBundle bundle)
    {
        if (!openedBundles.TryGetValue(bundle.Handle.Value, out string? id)) throw new InvalidOperationException("Test bundle handle is not open.");
        return files[id].OrderBy(entry => entry.Key, StringComparer.Ordinal)
            .Select(entry =>
            {
                (ContentSha256 digest, ulong length) = entry.Value.Identity();
                return new ContentReferenceInfo(entry.Key, digest, length);
            })
            .ToArray();
    }

    public ContentReference OpenBundleReference(ContentBundleReferenceRequest request)
    {
        if (!openedBundles.TryGetValue(request.Bundle.Handle.Value, out string? id)
            || !files[id].ContainsKey(request.Path)) throw new FileNotFoundException("Test bundle file is not declared.", request.Path);
        OpenedReferences.Add((id, request.Path));
        return Reference(id, request.Path);
    }

    private ContentReference Reference(string bundle, string path)
    {
        ulong handle = nextHandle++;
        references.Add(handle, (bundle, path));
        return new(new ContentReferenceHandle(handle), () => references.Remove(handle));
    }

    public ContentReference AdmitReference(ContentAdmissionRequest request) =>
        throw new NotSupportedException($"This fake serves bundle files, so generated reference '{request.Path}' cannot be admitted.");

    public ContentReference OpenReference(ContentOpenRequest request) => throw new NotSupportedException();

    /// <summary>Resolves a content path inside an open bundle with a known root, checking its digest as the Engine does.</summary>
    public ContentReference ResolveReference(ContentResolveRequest request)
    {
        foreach (string bundle in openedBundles.Values.Distinct(StringComparer.Ordinal))
        {
            if (!roots.TryGetValue(bundle, out string? root) || !request.Path.StartsWith(root + "/", StringComparison.Ordinal)) continue;
            string path = request.Path[(root.Length + 1)..];
            if (!files[bundle].TryGetValue(path, out BundleFile? file)) break;
            if (file.Identity().Digest != request.Sha256) throw new InvalidOperationException($"Test bundle file '{request.Path}' has another digest.");
            OpenedReferences.Add((bundle, path));
            return Reference(bundle, path);
        }

        throw new FileNotFoundException("No open test bundle carries the requested content path.", request.Path);
    }

    public ReadOnlyMemory<ContentReferenceInfo> ReadReferenceInfo(ContentReference reference)
    {
        (string bundle, string path) = references[reference.Handle.Value];
        (ContentSha256 digest, ulong length) = files[bundle][path].Identity();
        return new[] { new ContentReferenceInfo(path, digest, length) };
    }

    public ReadOnlyMemory<byte> ReadBytes(ContentReadBytesRequest request)
    {
        (string bundle, string path) = references[request.Reference.Handle.Value];
        ReadFiles.Add((bundle, path));
        byte[] body = files[bundle][path].Read();
        if (request.Offset > (ulong)body.Length) throw new InvalidOperationException($"Read of '{path}' starts past its bytes.");
        int available = checked((int)Math.Min(request.MaxBytes, (ulong)body.Length - request.Offset));
        return body.AsMemory(checked((int)request.Offset), available);
    }
}
