using Rusty.Engine;
using static WorldRpg.Rulesets.Daggerfall.Tests.TestSessions;

namespace WorldRpg.Rulesets.Daggerfall.Tests;

internal sealed class ContentFake : IContentService
{

    public PortableAsset LoadPortableAsset(PortableAssetLoadRequest request) => throw new NotSupportedException();
    public PortableAssetReadoutResult ReadPortableAsset(PortableAsset asset) => throw new NotSupportedException();
    public ContentReference OpenPortableAssetMember(PortableAssetMemberRequest request) => throw new NotSupportedException();
    // The pinned pair grew a bundle surface. Nothing in this product opens a bundle yet - content is
    // admitted as one snapshot - so the fake refuses these rather than pretending a bundle exists:
    // a test double that answered with an empty bundle would hide a caller that started using one.
    public ContentReference AdmitReference(ContentAdmissionRequest request)
    {
        // Admitting generated bytes registers them under their path exactly as an opened file is, so a
        // read of the returned reference answers the bytes that were admitted.
        byte[] body = request.Bytes.ToArray();
        Add(request.Path, Digest(body), body);
        return ResolveReference(new ContentResolveRequest(request.Path, values[request.Path]));
    }

    public ReadOnlyMemory<ContentBundleInfo> ListBundles() =>
        throw new NotSupportedException("This fake admits one content snapshot and carries no bundles.");

    public ContentBundle OpenBundle(ContentBundleOpenRequest request) =>
        throw new NotSupportedException($"This fake admits one content snapshot, so bundle '{request}' cannot be opened.");

    public ReadOnlyMemory<ContentReferenceInfo> ReadBundleFiles(ContentBundle bundle) =>
        throw new NotSupportedException("This fake admits one content snapshot and carries no bundle files.");

    public ContentReference OpenBundleReference(ContentBundleReferenceRequest request) =>
        throw new NotSupportedException($"This fake admits one content snapshot, so bundle reference '{request}' cannot be opened.");

    private readonly List<string> releases;
    private readonly Dictionary<string, ContentSha256> values = new(StringComparer.Ordinal);
    private readonly Dictionary<string, byte[]> bodies = new(StringComparer.Ordinal);
    private readonly Dictionary<string, int> reads = new(StringComparer.Ordinal);
    private readonly Dictionary<ulong, KeyValuePair<string, ContentSha256>> references = [];
    private ulong nextHandle = 1;

    internal ContentFake(string path, ContentSha256 hash, List<string> releaseLog) : this(releaseLog) => Add(path, hash);
    internal ContentFake(List<string> releaseLog) => releases = releaseLog;

    internal void Add(string contentPath, ContentSha256 contentHash) => values[contentPath] = contentHash;

    /// <summary>Admits one file with the bytes an admitted read returns for it.</summary>
    internal void Add(string contentPath, byte[] body) => Add(contentPath, Digest(body), body);

    internal void Add(string contentPath, ContentSha256 contentHash, byte[] body)
    {
        values[contentPath] = contentHash;
        bodies[contentPath] = body;
    }

    public ContentReference OpenReference(ContentOpenRequest request) => ResolveReference(new ContentResolveRequest(request.Path, values[request.Path]));

    public ContentReference ResolveReference(ContentResolveRequest request)
    {
        ResolveCalls++;
        if (!values.TryGetValue(request.Path, out ContentSha256 known) || known != request.Sha256) throw new InvalidOperationException("Unexpected content reference.");
        ulong value = nextHandle++;
        references.Add(value, new KeyValuePair<string, ContentSha256>(request.Path, known));
        return new ContentReference(new ContentReferenceHandle(value), () => releases.Add("content"));
    }

    /// <summary>How many admitted reads this fake served for one path, which shows how it was chunked.</summary>
    internal int Reads(string path) => reads.GetValueOrDefault(path);

    public ReadOnlyMemory<ContentReferenceInfo> ReadReferenceInfo(ContentReference reference)
    {
        KeyValuePair<string, ContentSha256> item = references[reference.Handle.Value];
        ulong length = bodies.TryGetValue(item.Key, out byte[]? body) ? (ulong)body.Length : 1;
        return new[] { new ContentReferenceInfo(item.Key, item.Value, length) };
    }

    public ReadOnlyMemory<byte> ReadBytes(ContentReadBytesRequest request)
    {
        string path = references[request.Reference.Handle.Value].Key;
        // The Engine serves at most one mebibyte per admitted read, so this fake does too: a fake
        // that answered a larger request would hide a reader that asked for a whole artifact.
        if (request.MaxBytes > 1024 * 1024) throw new InvalidOperationException($"Admitted content reads are bounded to one mebibyte, not {request.MaxBytes}.");
        reads[path] = reads.GetValueOrDefault(path) + 1;
        if (!bodies.TryGetValue(path, out byte[]? body)) return ReadOnlyMemory<byte>.Empty;
        if (request.Offset > (ulong)body.Length) throw new InvalidOperationException($"Read of '{path}' starts past its admitted bytes.");
        int available = checked((int)Math.Min(request.MaxBytes, (ulong)body.Length - request.Offset));
        return body.AsMemory(checked((int)request.Offset), available);
    }
    internal int ResolveCalls { get; private set; }
}

/// <summary>Build-declared bundles for full-product tests; bodies stay outside the eager snapshot.</summary>
internal sealed class BundleContentFake : IContentService
{

    public PortableAsset LoadPortableAsset(PortableAssetLoadRequest request) => throw new NotSupportedException();
    public PortableAssetReadoutResult ReadPortableAsset(PortableAsset asset) => throw new NotSupportedException();
    public ContentReference OpenPortableAssetMember(PortableAssetMemberRequest request) => throw new NotSupportedException();
    private readonly Dictionary<string, Dictionary<string, byte[]>> files = new(StringComparer.Ordinal);
    private readonly Dictionary<ulong, string> openedBundles = [];
    private ulong nextHandle = 1;

    /// <summary>Every bundle file the product opened, in order, as its bundle and its path inside it.</summary>
    internal List<(string Bundle, string Path)> OpenedReferences { get; } = [];

    internal void Add(string bundle, string path, byte[] bytes)
    {
        if (!files.TryGetValue(bundle, out Dictionary<string, byte[]>? values)) files.Add(bundle, values = new(StringComparer.Ordinal));
        values.Add(path, bytes);
    }

    public ReadOnlyMemory<ContentBundleInfo> ListBundles() => files
        .OrderBy(entry => entry.Key, StringComparer.Ordinal)
        .Select(entry => new ContentBundleInfo(entry.Key, checked((ulong)entry.Value.Count), checked((ulong)entry.Value.Values.Sum(bytes => bytes.Length))))
        .ToArray();

    public ContentBundle OpenBundle(ContentBundleOpenRequest request)
    {
        if (!files.ContainsKey(request.Id)) throw new FileNotFoundException("Test bundle is not declared.", request.Id);
        ulong handle = nextHandle++;
        openedBundles.Add(handle, request.Id);
        return new(new ContentBundleHandle(handle), () => openedBundles.Remove(handle));
    }

    public ReadOnlyMemory<ContentReferenceInfo> ReadBundleFiles(ContentBundle bundle)
    {
        if (!openedBundles.TryGetValue(bundle.Handle.Value, out string? id)) throw new InvalidOperationException("Test bundle handle is not open.");
        return files[id].OrderBy(entry => entry.Key, StringComparer.Ordinal)
            .Select(entry => new ContentReferenceInfo(entry.Key, Digest(entry.Value), checked((ulong)entry.Value.Length)))
            .ToArray();
    }

    public ContentReference OpenBundleReference(ContentBundleReferenceRequest request)
    {
        if (!openedBundles.TryGetValue(request.Bundle.Handle.Value, out string? id)
            || !files[id].ContainsKey(request.Path)) throw new FileNotFoundException("Test bundle file is not declared.", request.Path);
        OpenedReferences.Add((id, request.Path));
        return new(new ContentReferenceHandle(nextHandle++), static () => { });
    }

    public ContentReference AdmitReference(ContentAdmissionRequest request) =>
        throw new NotSupportedException($"This fake serves bundle files, so generated reference '{request.Path}' cannot be admitted.");

    public ContentReference OpenReference(ContentOpenRequest request) => throw new NotSupportedException();
    public ContentReference ResolveReference(ContentResolveRequest request) => throw new NotSupportedException();
    public ReadOnlyMemory<ContentReferenceInfo> ReadReferenceInfo(ContentReference reference) => throw new NotSupportedException();
    public ReadOnlyMemory<byte> ReadBytes(ContentReadBytesRequest request) => throw new NotSupportedException();
}
