using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Daggerfall.Import.Arena2;
using Daggerfall.Import.Normalization;
using Daggerfall.Import.Normalized;

namespace Daggerfall.Import.Publication;

/// <summary>
/// The canonical typed sidecar for generated dungeon media. It retains source
/// interpretation and regenerated atlas facts, but never embeds source or
/// generated bytes.
/// </summary>
public sealed record DungeonMediaManifestSidecar(
    int SchemaVersion,
    NormalizedMediaManifest Media,
    IReadOnlyList<DungeonMaterialMediaManifest> Materials,
    IReadOnlyList<DungeonBillboardMediaManifest> Billboards,
    IReadOnlyList<DungeonActorMediaManifest> Actors)
{
    public const int CurrentSchemaVersion = 1;
}

/// <summary>One generated dungeon material texture and its resource meaning.</summary>
public sealed record DungeonMaterialMediaManifest(
    string TextureResourceId,
    string MaterialResourceId,
    uint MaterialSlot,
    ushort TextureArchive,
    ushort TextureRecord,
    int Width,
    int Height,
    string MediaId);

/// <summary>One generated dungeon billboard and its source-backed frame facts.</summary>
public sealed record DungeonBillboardMediaManifest(
    string SpriteResourceId,
    ushort TextureArchive,
    ushort TextureRecord,
    NormalizedVector2 Pivot,
    NormalizedVector2 WorldSize,
    DungeonSpritePlaybackSource? SourcePlayback,
    DungeonSpritePlaybackSource? Playback,
    IReadOnlyList<DungeonMediaFrameLayout> Frames,
    string MediaId);

/// <summary>One generated corpse sprite selected for a dungeon actor.</summary>
public sealed record DungeonActorCorpseMediaManifest(
    ushort TextureArchive,
    ushort TextureRecord,
    NormalizedVector2 Pivot,
    NormalizedVector2 WorldSize,
    NormalizedVector2 SourceWorldSize,
    DungeonMediaFrameLayout Frame,
    string MediaId);

/// <summary>One generated dungeon actor atlas and its source-state layout.</summary>
public sealed record DungeonActorMediaManifest(
    string ActorResourceId,
    byte MobileId,
    string SourceName,
    DungeonActorSpriteState PreferredRestState,
    DungeonActorAttackSequenceSource SourceAttackSequence,
    string SpriteResourceId,
    NormalizedVector2 Pivot,
    NormalizedVector2 WorldSize,
    NormalizedVector2 SourceWorldSize,
    IReadOnlyList<DungeonActorSpriteStateLayout> States,
    DungeonActorCorpseMediaManifest? Corpse,
    string MediaId);

/// <summary>
/// The canonical typed sidecar for selected classic Daggerfall media. It owns
/// no playback and only references generated artifacts by logical media ID.
/// </summary>
public sealed record ClassicMediaManifestSidecar(
    int SchemaVersion,
    NormalizedMediaManifest Media,
    IReadOnlyList<ClassicWeaponActionManifest> WeaponActions,
    IReadOnlyList<ClassicEffectManifest> Effects,
    IReadOnlyList<ClassicAudioManifest> Audio,
    IReadOnlyList<ClassicUiImageManifest> UiImages,
    IReadOnlyList<ClassicInventoryIconManifest> InventoryIcons,
    ClassicFontManifest Font,
    IReadOnlyList<ClassicAuthoredUiAssetManifest> AuthoredUiAssets)
{
    public const int CurrentSchemaVersion = 1;
}

/// <summary>
/// Joins spatial normalization with independently generated dungeon and
/// classic media into one portable publication closure. This is deliberately
/// an offline composition seam: it creates no Engine resources and does not
/// inspect a directory.
/// </summary>
public sealed record Arena2MediaBundlePublication(
    NormalizedImportDocument Document,
    ImportPublicationPlan Plan)
{
    public const string DungeonMediaManifestRelativePath = "media/dungeon/manifest.json";
    public const string ClassicMediaManifestRelativePath = "media/classic/manifest.json";
    public const string NormalizedDocumentRelativePath = "normalized.json";

    // These are source-format record positions, not presentation policy. They
    // keep a manually mutated publication from relabeling the fixed dagger
    // action table after its generated atlas has been validated.
    private static readonly IReadOnlyDictionary<ClassicDaggerWeaponAction, int> WeaponActionSourceRecords =
        new Dictionary<ClassicDaggerWeaponAction, int>
        {
            [ClassicDaggerWeaponAction.Idle] = 0,
            [ClassicDaggerWeaponAction.StrikeDown] = 1,
            [ClassicDaggerWeaponAction.StrikeDownLeft] = 2,
            [ClassicDaggerWeaponAction.StrikeLeft] = 3,
            [ClassicDaggerWeaponAction.StrikeRight] = 4,
            [ClassicDaggerWeaponAction.StrikeDownRight] = 5,
            [ClassicDaggerWeaponAction.StrikeUp] = 6,
        };

    internal static int ExpectedWeaponActionSourceRecordOrdinal(ClassicDaggerWeaponAction action) =>
        WeaponActionSourceRecords.TryGetValue(action, out int sourceRecord)
            ? sourceRecord
            : throw new ArgumentOutOfRangeException(nameof(action), "The weapon action is not part of the fixed classic source closure.");

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
        NumberHandling = JsonNumberHandling.Strict,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase) },
    };

    /// <summary>
    /// Creates a complete content-addressed publication. Source records from
    /// the spatial and classic passes are merged into the serialized normalized
    /// document; an equal source path must retain the exact same schema, digest,
    /// and length in both passes.
    /// </summary>
    public static Arena2MediaBundlePublication Create(
        DungeonNormalizationResult dungeon,
        Arena2DungeonMediaPublication dungeonMedia,
        Arena2ClassicMediaPublication classicMedia)
    {
        ArgumentNullException.ThrowIfNull(dungeon);
        ArgumentNullException.ThrowIfNull(dungeonMedia);
        ArgumentNullException.ThrowIfNull(classicMedia);
        dungeon.Validate();

        ValidateDungeonMedia(dungeonMedia);
        ValidateClassicMedia(classicMedia);

        ImportProvenance mergedProvenance = MergeProvenance(dungeon.Document.Provenance, classicMedia.Sources);
        NormalizedImportDocument document = (dungeon.Document with { Provenance = mergedProvenance }).Canonicalize();
        document.Validate();
        dungeon.SpatialPublication.ValidateAgainst(document);

        DungeonMediaManifestSidecar dungeonSidecar = CreateDungeonSidecar(dungeon.SpatialPublication, dungeonMedia);
        ClassicMediaManifestSidecar classicSidecar = CreateClassicSidecar(classicMedia);
        ValidatePersistedSidecars(dungeonSidecar, classicSidecar);
        byte[] dungeonSidecarBytes = SerializeSidecar(dungeonSidecar);
        byte[] classicSidecarBytes = SerializeSidecar(classicSidecar);

        Dictionary<string, string> spatialPathsById = dungeon.SpatialPublication.Artifacts
            .ToDictionary(artifact => artifact.Id, artifact => artifact.RelativePath, StringComparer.Ordinal);
        List<ImportPublicationArtifact> artifacts = [
            .. dungeon.SpatialPublication.Artifacts.Select(artifact => new ImportPublicationArtifact(
                artifact.RelativePath,
                artifact.Bytes.Span,
                artifact.DependsOnArtifactIds.Select(id => spatialPathsById[id]).ToArray())),
            .. dungeonMedia.Artifacts,
            .. classicMedia.Artifacts,
            new ImportPublicationArtifact(
                DungeonMediaManifestRelativePath,
                dungeonSidecarBytes,
                dungeonMedia.Artifacts.Select(artifact => artifact.RelativePath).ToArray()),
            new ImportPublicationArtifact(
                ClassicMediaManifestRelativePath,
                classicSidecarBytes,
                classicMedia.Artifacts.Select(artifact => artifact.RelativePath).ToArray()),
        ];

        string[] normalizedDependencies = [
            .. dungeon.SpatialPublication.Artifacts.Select(artifact => artifact.RelativePath),
            DungeonMediaManifestRelativePath,
            ClassicMediaManifestRelativePath,
        ];
        artifacts.Add(new ImportPublicationArtifact(
            NormalizedDocumentRelativePath,
            NormalizedImportSerializer.Serialize(document),
            normalizedDependencies));

        return new(document, ImportPublicationPlan.Create(mergedProvenance, artifacts));
    }

    /// <summary>
    /// Validates the two generated media sidecars before any consumer projects
    /// them. This is the canonical persisted-sidecar boundary; inspection and
    /// authoring tools must call it rather than growing their own partial view.
    /// </summary>
    public static void ValidatePersistedSidecars(DungeonMediaManifestSidecar dungeon, ClassicMediaManifestSidecar classic)
    {
        try
        {
            ArgumentNullException.ThrowIfNull(dungeon);
            ArgumentNullException.ThrowIfNull(classic);
            if (dungeon.SchemaVersion != DungeonMediaManifestSidecar.CurrentSchemaVersion
                || classic.SchemaVersion != ClassicMediaManifestSidecar.CurrentSchemaVersion)
            {
                throw new InvalidOperationException("A persisted media sidecar schema version is not supported.");
            }

            IReadOnlyDictionary<string, NormalizedMediaDescriptor> dungeonMedia = ValidatePersistedMedia(dungeon.Media, "dungeon");
            IReadOnlyDictionary<string, NormalizedMediaDescriptor> classicMedia = ValidatePersistedMedia(classic.Media, "classic");
            ValidatePersistedDungeonSidecar(dungeon, dungeonMedia);
            ValidatePersistedClassicSidecar(classic, classicMedia);
        }
        catch (Exception exception) when (exception is ArgumentException or InvalidOperationException or NullReferenceException)
        {
            throw new FormatException("The persisted media sidecars violate the canonical publication contract.", exception);
        }
    }

    private static IReadOnlyDictionary<string, NormalizedMediaDescriptor> ValidatePersistedMedia(NormalizedMediaManifest manifest, string family)
    {
        ArgumentNullException.ThrowIfNull(manifest);
        ArgumentNullException.ThrowIfNull(manifest.Resources);
        if (manifest.Resources.Count == 0 || manifest.Resources.Any(resource => resource is null)
            || manifest.Resources.Select(resource => resource.Id).Distinct(StringComparer.Ordinal).Count() != manifest.Resources.Count
            || manifest.Resources.Select(resource => resource.RelativePath).Distinct(StringComparer.Ordinal).Count() != manifest.Resources.Count)
        {
            throw new InvalidOperationException($"Persisted {family} media must contain unique non-null descriptors and paths.");
        }

        foreach (NormalizedMediaDescriptor resource in manifest.Resources)
        {
            NormalizedImportDocument.RequireLogicalId(resource.Id, nameof(resource.Id));
            NormalizedImportDocument.RequireLogicalPath(resource.RelativePath, nameof(resource.RelativePath));
            resource.ContentDigest.Validate();
            if (!Enum.IsDefined(resource.Kind) || string.IsNullOrWhiteSpace(resource.MimeType) || resource.ByteLength <= 0
                || resource.SourceWidth < 0 || resource.SourceHeight < 0 || resource.AtlasWidth < 0 || resource.AtlasHeight < 0
                || resource.Frames is null || resource.Frames.Count == 0 && (resource.AtlasWidth != 0 || resource.AtlasHeight != 0)
                || resource.Frames.Count != 0 && (resource.AtlasWidth <= 0 || resource.AtlasHeight <= 0)
                || resource.Frames.Select(frame => frame.Id).Distinct(StringComparer.Ordinal).Count() != resource.Frames.Count
                || resource.Frames.Select(frame => frame.FrameIndex).Distinct().Count() != resource.Frames.Count
                || resource.Frames.OrderBy(frame => frame.FrameIndex).Select((frame, index) => frame.FrameIndex != index).Any(value => value)
                || resource.Frames.Any(frame => frame is null || string.IsNullOrWhiteSpace(frame.Id) || frame.FrameIndex < 0 || frame.X < 0 || frame.Y < 0
                    || frame.Width <= 0 || frame.Height <= 0 || frame.SourceWidth <= 0 || frame.SourceHeight <= 0
                    || (long)frame.X + frame.Width > resource.AtlasWidth || (long)frame.Y + frame.Height > resource.AtlasHeight))
            {
                throw new InvalidOperationException($"Persisted {family} descriptor '{resource.Id}' is invalid.");
            }

            if (resource.DisplayName is not null && (string.IsNullOrWhiteSpace(resource.DisplayName) || resource.DisplayName.Any(char.IsControl)))
            {
                throw new InvalidOperationException($"Persisted {family} descriptor '{resource.Id}' has an invalid display name.");
            }

            resource.Pivot?.Validate(nameof(resource.Pivot));
            resource.DisplaySize?.Validate(nameof(resource.DisplaySize));
            if (resource.DisplaySize is { X: <= 0F } or { Y: <= 0F }
                || resource.FramesPerSecond is <= 0F || resource.FramesPerSecond is { } rate && !float.IsFinite(rate)
                || resource.Sequence is { Count: 0 } || resource.Sequence?.Any(index => index < 0 || index >= resource.Frames.Count) == true)
            {
                throw new InvalidOperationException($"Persisted {family} descriptor '{resource.Id}' has invalid authored presentation values.");
            }
        }

        return manifest.Resources.ToDictionary(resource => resource.Id, StringComparer.Ordinal);
    }

    private static void ValidatePersistedDungeonSidecar(DungeonMediaManifestSidecar sidecar, IReadOnlyDictionary<string, NormalizedMediaDescriptor> media)
    {
        ArgumentNullException.ThrowIfNull(sidecar.Materials);
        ArgumentNullException.ThrowIfNull(sidecar.Billboards);
        ArgumentNullException.ThrowIfNull(sidecar.Actors);
        if (sidecar.Materials.Any(value => value is null) || sidecar.Billboards.Any(value => value is null) || sidecar.Actors.Any(value => value is null)
            || sidecar.Materials.Select(value => value.TextureResourceId).Distinct(StringComparer.Ordinal).Count() != sidecar.Materials.Count
            || sidecar.Materials.Select(value => value.MaterialResourceId).Distinct(StringComparer.Ordinal).Count() != sidecar.Materials.Count
            || sidecar.Materials.Select(value => value.MaterialSlot).Distinct().Count() != sidecar.Materials.Count
            || sidecar.Billboards.Select(value => value.SpriteResourceId).Distinct(StringComparer.Ordinal).Count() != sidecar.Billboards.Count
            || sidecar.Actors.Select(value => value.ActorResourceId).Distinct(StringComparer.Ordinal).Count() != sidecar.Actors.Count
            || sidecar.Actors.Select(value => value.MobileId).Distinct().Count() != sidecar.Actors.Count)
        {
            throw new InvalidOperationException("Persisted dungeon sidecar identifiers must be unique.");
        }

        foreach (DungeonMaterialMediaManifest material in sidecar.Materials)
        {
            NormalizedImportDocument.RequireLogicalId(material.TextureResourceId, nameof(material.TextureResourceId));
            NormalizedImportDocument.RequireLogicalId(material.MaterialResourceId, nameof(material.MaterialResourceId));
            NormalizedMediaDescriptor descriptor = RequirePersistedDescriptor(media, material.MediaId, NormalizedMediaKind.Texture, "dungeon material");
            if (material.Width <= 0 || material.Height <= 0 || descriptor.SourceWidth != material.Width || descriptor.SourceHeight != material.Height)
            {
                throw new InvalidOperationException("Persisted dungeon material dimensions do not match the generated descriptor.");
            }
        }

        foreach (DungeonBillboardMediaManifest billboard in sidecar.Billboards)
        {
            NormalizedImportDocument.RequireLogicalId(billboard.SpriteResourceId, nameof(billboard.SpriteResourceId));
            NormalizedMediaDescriptor descriptor = RequirePersistedDescriptor(media, billboard.MediaId, NormalizedMediaKind.Billboard, "dungeon billboard");
            ValidatePersistedSpriteFrames(descriptor, billboard.Frames, "dungeon billboard");
            billboard.Pivot.Validate(nameof(billboard.Pivot));
            billboard.WorldSize.Validate(nameof(billboard.WorldSize));
            if (billboard.WorldSize.X <= 0F || billboard.WorldSize.Y <= 0F)
            {
                throw new InvalidOperationException("Persisted dungeon billboard world size must be positive.");
            }

            billboard.SourcePlayback?.Validate();
            billboard.Playback?.Validate();
            if (descriptor.Pivot is not null && descriptor.Pivot != billboard.Pivot
                || descriptor.DisplaySize is not null && descriptor.DisplaySize != billboard.WorldSize
                || descriptor.FramesPerSecond is not null && (billboard.Playback is null || descriptor.FramesPerSecond != billboard.Playback.FramesPerSecond)
                || descriptor.Loop is not null && (billboard.Playback is null || descriptor.Loop != billboard.Playback.Loops))
            {
                throw new InvalidOperationException("Persisted dungeon billboard presentation disagrees with its generated descriptor.");
            }
        }

        string[] directProjectedMediaIds = [.. sidecar.Billboards.Select(billboard => billboard.MediaId), .. sidecar.Actors.Select(actor => actor.MediaId)];
        if (directProjectedMediaIds.Distinct(StringComparer.Ordinal).Count() != directProjectedMediaIds.Length)
        {
            throw new InvalidOperationException("Persisted sprite projections cannot share a media ID.");
        }

        HashSet<string> projectedMediaIds = [.. directProjectedMediaIds];
        foreach (DungeonActorMediaManifest actor in sidecar.Actors)
        {
            NormalizedImportDocument.RequireLogicalId(actor.ActorResourceId, nameof(actor.ActorResourceId));
            NormalizedImportDocument.RequireLogicalId(actor.SpriteResourceId, nameof(actor.SpriteResourceId));
            if (string.IsNullOrWhiteSpace(actor.SourceName) || !Enum.IsDefined(actor.PreferredRestState) || actor.States is null || actor.States.Count == 0)
            {
                throw new InvalidOperationException("Persisted dungeon actor metadata is incomplete.");
            }

            ArgumentNullException.ThrowIfNull(actor.SourceAttackSequence);
            actor.SourceAttackSequence.Validate();
            NormalizedMediaDescriptor descriptor = RequirePersistedDescriptor(media, actor.MediaId, NormalizedMediaKind.EnemySprite, "dungeon actor");
            ValidatePersistedSpriteFrames(descriptor, actor.States.SelectMany(state => state.Frames).ToArray(), "dungeon actor");
            actor.Pivot.Validate(nameof(actor.Pivot));
            actor.WorldSize.Validate(nameof(actor.WorldSize));
            actor.SourceWorldSize.Validate(nameof(actor.SourceWorldSize));
            if (actor.WorldSize.X <= 0F || actor.WorldSize.Y <= 0F || actor.SourceWorldSize.X <= 0F || actor.SourceWorldSize.Y <= 0F
                || actor.States.Any(state => state is null) || actor.States.Select(state => state.State).Distinct().Count() != actor.States.Count
                || !actor.States.Any(state => state.State == actor.PreferredRestState))
            {
                throw new InvalidOperationException("Persisted dungeon actor state or display facts are invalid.");
            }

            foreach (DungeonActorSpriteStateLayout state in actor.States)
            {
                if (state.FramesPerOrientation > int.MaxValue / 8)
                {
                    throw new InvalidOperationException("Persisted dungeon actor state frame count exceeds the supported range.");
                }

                state.Validate();
                ValidateStateRange(state);
                if (descriptor.FramesPerSecond is not null && state.Playback.FramesPerSecond != descriptor.FramesPerSecond
                    || descriptor.Loop is not null && state.Playback.Loops != descriptor.Loop)
                {
                    throw new InvalidOperationException("Persisted dungeon actor state timing disagrees with its descriptor.");
                }
            }

            if (descriptor.Pivot is not null && descriptor.Pivot != actor.Pivot
                || descriptor.DisplaySize is not null && descriptor.DisplaySize != actor.WorldSize)
            {
                throw new InvalidOperationException("Persisted dungeon actor presentation disagrees with its descriptor.");
            }

            if (actor.Corpse is not null)
            {
                if (!projectedMediaIds.Add(actor.Corpse.MediaId))
                {
                    throw new InvalidOperationException("Persisted sprite projections cannot share a media ID.");
                }

                NormalizedMediaDescriptor corpse = RequirePersistedDescriptor(media, actor.Corpse.MediaId, NormalizedMediaKind.EnemySprite, "dungeon corpse");
                ValidatePersistedSpriteFrames(corpse, [actor.Corpse.Frame], "dungeon corpse");
                actor.Corpse.Pivot.Validate(nameof(actor.Corpse.Pivot));
                actor.Corpse.WorldSize.Validate(nameof(actor.Corpse.WorldSize));
                actor.Corpse.SourceWorldSize.Validate(nameof(actor.Corpse.SourceWorldSize));
                if (corpse.Pivot is not null && corpse.Pivot != actor.Corpse.Pivot
                    || corpse.DisplaySize is not null && corpse.DisplaySize != actor.Corpse.WorldSize)
                {
                    throw new InvalidOperationException("Persisted dungeon corpse presentation disagrees with its descriptor.");
                }
            }
        }
    }

    private static void ValidatePersistedClassicSidecar(ClassicMediaManifestSidecar sidecar, IReadOnlyDictionary<string, NormalizedMediaDescriptor> media)
    {
        ArgumentNullException.ThrowIfNull(sidecar.WeaponActions);
        ArgumentNullException.ThrowIfNull(sidecar.Effects);
        NormalizedMediaDescriptor weapon = media.Values.SingleOrDefault(resource => resource.Kind == NormalizedMediaKind.WeaponSprite)
            ?? throw new InvalidOperationException("Persisted classic media has no weapon descriptor.");
        if (media.Values.Count(resource => resource.Kind == NormalizedMediaKind.WeaponSprite) != 1)
        {
            throw new InvalidOperationException("Persisted classic media has multiple weapon descriptors.");
        }

        if (weapon.Frames.Count == 0)
        {
            throw new InvalidOperationException("Persisted classic weapon metadata requires regenerated frames.");
        }

        ClassicDaggerWeaponAction[] actions = Enum.GetValues<ClassicDaggerWeaponAction>();
        if (sidecar.WeaponActions.Any(action => action is null) || sidecar.WeaponActions.Count != actions.Length
            || !sidecar.WeaponActions.Select(action => action.Action).SequenceEqual(actions))
        {
            throw new InvalidOperationException("Persisted classic weapon actions must contain the exact canonical action set.");
        }

        HashSet<int> coveredFrames = [];
        int expectedFrameStart = 0;
        foreach (ClassicWeaponActionManifest action in sidecar.WeaponActions)
        {
            action.Validate(weapon.Frames.Count);
            if (action.FrameStart != expectedFrameStart)
            {
                throw new InvalidOperationException("Persisted classic weapon actions must retain the canonical ordered frame ranges.");
            }
            if (action.SourceRecordOrdinal != ExpectedWeaponActionSourceRecordOrdinal(action.Action))
            {
                throw new InvalidOperationException("Persisted classic weapon actions have noncanonical source records.");
            }

            foreach (int frame in Enumerable.Range(action.FrameStart, action.FrameCount))
            {
                if (!coveredFrames.Add(frame))
                {
                    throw new InvalidOperationException("Persisted classic weapon actions overlap.");
                }
            }

            expectedFrameStart = checked(expectedFrameStart + action.FrameCount);
        }

        if (!coveredFrames.SetEquals(weapon.Frames.Select(frame => frame.FrameIndex)))
        {
            throw new InvalidOperationException("Persisted classic weapon actions do not cover the generated atlas.");
        }

        ValidateEffectProjections(sidecar.Effects, media);
        ArgumentNullException.ThrowIfNull(sidecar.Audio);
        ArgumentNullException.ThrowIfNull(sidecar.UiImages);
        ArgumentNullException.ThrowIfNull(sidecar.InventoryIcons);
        ArgumentNullException.ThrowIfNull(sidecar.Font);
        ArgumentNullException.ThrowIfNull(sidecar.AuthoredUiAssets);
        if (sidecar.Audio.Any(audio => audio is null) || sidecar.UiImages.Any(image => image is null) || sidecar.InventoryIcons.Any(icon => icon is null)
            || sidecar.AuthoredUiAssets.Any(asset => asset is null))
        {
            throw new InvalidOperationException("Persisted classic sidecar lists cannot contain null entries.");
        }

        foreach (ClassicAudioManifest audio in sidecar.Audio)
        {
            audio.Validate();
            RequirePersistedDescriptor(media, audio.MediaId, NormalizedMediaKind.Audio, "classic audio");
        }

        foreach (ClassicUiImageManifest image in sidecar.UiImages)
        {
            image.Validate();
            RequirePersistedDescriptor(media, image.MediaId, NormalizedMediaKind.UserInterface, "classic UI image");
        }

        foreach (ClassicInventoryIconManifest icon in sidecar.InventoryIcons)
        {
            icon.Validate();
            RequirePersistedDescriptor(media, icon.MediaId, NormalizedMediaKind.UserInterface, "classic inventory icon");
        }

        sidecar.Font.Validate();
        RequirePersistedDescriptor(media, sidecar.Font.MediaId, NormalizedMediaKind.Font, "classic font");
        if (sidecar.AuthoredUiAssets.Select(asset => asset.Id).Distinct(StringComparer.Ordinal).Count() != sidecar.AuthoredUiAssets.Count
            || sidecar.AuthoredUiAssets.Select(asset => asset.RelativePath).Distinct(StringComparer.Ordinal).Count() != sidecar.AuthoredUiAssets.Count)
        {
            throw new InvalidOperationException("Persisted classic authored UI assets must have unique IDs and paths.");
        }

        foreach (ClassicAuthoredUiAssetManifest asset in sidecar.AuthoredUiAssets)
        {
            NormalizedImportDocument.RequireLogicalId(asset.Id, nameof(asset.Id));
            NormalizedImportDocument.RequireLogicalPath(asset.RelativePath, nameof(asset.RelativePath));
            NormalizedImportDocument.RequireLogicalPath(asset.SourceLabel, nameof(asset.SourceLabel));
            if (string.IsNullOrWhiteSpace(asset.Generator) || string.IsNullOrWhiteSpace(asset.Prompt))
            {
                throw new InvalidOperationException("Persisted classic authored UI metadata is incomplete.");
            }

            NormalizedMediaDescriptor descriptor = RequirePersistedDescriptor(media, asset.Id, NormalizedMediaKind.UserInterface, "classic authored UI");
            if (!StringComparer.Ordinal.Equals(descriptor.RelativePath, asset.RelativePath))
            {
                throw new InvalidOperationException("Persisted classic authored UI metadata does not match its descriptor path.");
            }
        }
    }

    private static NormalizedMediaDescriptor RequirePersistedDescriptor(IReadOnlyDictionary<string, NormalizedMediaDescriptor> media, string id, NormalizedMediaKind kind, string subject)
    {
        NormalizedImportDocument.RequireLogicalId(id, nameof(id));
        if (!media.TryGetValue(id, out NormalizedMediaDescriptor? descriptor) || descriptor.Kind != kind)
        {
            throw new InvalidOperationException($"Persisted {subject} identifies an unknown or incompatible media descriptor '{id}'.");
        }

        return descriptor;
    }

    private static void ValidatePersistedSpriteFrames(NormalizedMediaDescriptor descriptor, IReadOnlyList<DungeonMediaFrameLayout> layouts, string subject)
    {
        ArgumentNullException.ThrowIfNull(layouts);
        if (descriptor.Frames.Count == 0 || layouts.Count != descriptor.Frames.Count || layouts.Any(layout => layout is null)
            || layouts.Select(layout => layout.AtlasFrameIndex).Distinct().Count() != layouts.Count)
        {
            throw new InvalidOperationException($"Persisted {subject} frame layouts do not cover the generated descriptor exactly.");
        }

        Dictionary<int, NormalizedAtlasFrame> frames = descriptor.Frames.ToDictionary(frame => frame.FrameIndex);
        foreach (DungeonMediaFrameLayout layout in layouts)
        {
            layout.Validate();
            if (!frames.TryGetValue(layout.AtlasFrameIndex, out NormalizedAtlasFrame? frame) || frame != layout.AtlasFrame)
            {
                throw new InvalidOperationException($"Persisted {subject} frame layout differs from generated atlas metadata.");
            }
        }
    }

    private static ImportProvenance MergeProvenance(ImportProvenance dungeon, IReadOnlyList<LogicalSourceRecord> classicSources)
    {
        ArgumentNullException.ThrowIfNull(dungeon);
        ArgumentNullException.ThrowIfNull(classicSources);
        dungeon.Validate();
        Dictionary<string, LogicalSourceRecord> sources = new(StringComparer.Ordinal);
        foreach (LogicalSourceRecord source in dungeon.Sources.Concat(classicSources).OrderBy(source => source.SourcePath, StringComparer.Ordinal))
        {
            ArgumentNullException.ThrowIfNull(source);
            source.Validate();
            if (!sources.TryGetValue(source.SourcePath, out LogicalSourceRecord? existing))
            {
                sources.Add(source.SourcePath, source);
                continue;
            }

            if (existing.SchemaVersion != source.SchemaVersion
                || existing.SourceSchemaVersion != source.SourceSchemaVersion
                || existing.ByteLength != source.ByteLength
                || existing.ContentDigest != source.ContentDigest)
            {
                throw new InvalidOperationException($"Logical source '{source.SourcePath}' does not agree across normalized import passes.");
            }
        }

        return new(
            ImportProvenance.CurrentSchemaVersion,
            dungeon.ImporterId,
            dungeon.ImporterVersion,
            sources.Values.OrderBy(source => source.SourcePath, StringComparer.Ordinal).ToArray());
    }

    private static DungeonMediaManifestSidecar CreateDungeonSidecar(DungeonSpatialPublication spatial, Arena2DungeonMediaPublication publication)
    {
        ArgumentNullException.ThrowIfNull(spatial);
        ArgumentNullException.ThrowIfNull(publication);
        Dictionary<string, uint> slotByMaterial = spatial.MaterialSlots
            .ToDictionary(binding => binding.MaterialResourceId, binding => binding.Slot, StringComparer.Ordinal);
        if (slotByMaterial.Count != spatial.MaterialSlots.Count)
        {
            throw new InvalidOperationException("Spatial publication has duplicate material-slot resource IDs.");
        }

        string[] generatedMaterials = publication.MaterialTextures
            .Select(media => media.MaterialResourceId)
            .OrderBy(id => id, StringComparer.Ordinal)
            .ToArray();
        if (generatedMaterials.Distinct(StringComparer.Ordinal).Count() != generatedMaterials.Length
            || !generatedMaterials.SequenceEqual(slotByMaterial.Keys.OrderBy(id => id, StringComparer.Ordinal), StringComparer.Ordinal))
        {
            throw new InvalidOperationException("Dungeon media materials must exactly match the static-mesh material-slot publication.");
        }

        return new(
        DungeonMediaManifestSidecar.CurrentSchemaVersion,
        CanonicalizeMedia(publication.MediaManifest),
        publication.MaterialTextures
            .OrderBy(media => media.TextureResourceId, StringComparer.Ordinal)
            .Select(media => new DungeonMaterialMediaManifest(
                media.TextureResourceId,
                media.MaterialResourceId,
                slotByMaterial[media.MaterialResourceId],
                media.TextureArchive,
                media.TextureRecord,
                media.Width,
                media.Height,
                media.Descriptor.Id))
            .ToArray(),
        publication.Billboards
            .OrderBy(media => media.SpriteResourceId, StringComparer.Ordinal)
            .Select(media => new DungeonBillboardMediaManifest(
                media.SpriteResourceId,
                media.TextureArchive,
                media.TextureRecord,
                media.Pivot,
                media.WorldSize,
                media.SourcePlayback,
                media.Playback,
                media.Frames.OrderBy(frame => frame.AtlasFrameIndex).ThenBy(frame => frame.SourceRecord).ThenBy(frame => frame.SourceFrame).ToArray(),
                media.Descriptor.Id))
            .ToArray(),
        publication.Actors
            .OrderBy(media => media.ActorResourceId, StringComparer.Ordinal)
            .Select(media => new DungeonActorMediaManifest(
                media.ActorResourceId,
                media.MobileId.Value,
                media.SourceName,
                media.PreferredRestState,
                media.SourceAttackSequence,
                media.SpriteResourceId,
                media.Pivot,
                media.WorldSize,
                media.SourceWorldSize,
                media.States.OrderBy(state => state.State).Select(CanonicalizeState).ToArray(),
                media.Corpse is null
                    ? null
                    : new DungeonActorCorpseMediaManifest(
                        media.Corpse.TextureArchive,
                        media.Corpse.TextureRecord,
                        media.Corpse.Pivot,
                        media.Corpse.WorldSize,
                        media.Corpse.SourceWorldSize,
                        media.Corpse.Frame,
                        media.Corpse.Descriptor.Id),
                media.Descriptor.Id))
            .ToArray());
    }

    private static ClassicMediaManifestSidecar CreateClassicSidecar(Arena2ClassicMediaPublication publication) => new(
        ClassicMediaManifestSidecar.CurrentSchemaVersion,
        CanonicalizeMedia(publication.MediaManifest),
        publication.WeaponActions.OrderBy(action => action.Action).ThenBy(action => action.SourceRecordOrdinal).ThenBy(action => action.FrameStart).ToArray(),
        publication.Effects.OrderBy(effect => effect.Effect).ThenBy(effect => effect.MediaId, StringComparer.Ordinal).ToArray(),
        publication.Audio.OrderBy(audio => audio.Clip).ThenBy(audio => audio.MediaId, StringComparer.Ordinal).ToArray(),
        publication.UiImages.OrderBy(image => image.Image).ThenBy(image => image.MediaId, StringComparer.Ordinal).ToArray(),
        publication.InventoryIcons.OrderBy(icon => icon.ItemId, StringComparer.Ordinal).ToArray(),
        publication.Font with { Glyphs = publication.Font.Glyphs.OrderBy(glyph => glyph.GlyphIndex).ToArray() },
        publication.AuthoredUiAssets.OrderBy(asset => asset.Id, StringComparer.Ordinal).ToArray());

    private static DungeonActorSpriteStateLayout CanonicalizeState(DungeonActorSpriteStateLayout state) => state with
    {
        Frames = state.Frames.OrderBy(frame => frame.AtlasFrameIndex).ThenBy(frame => frame.SourceRecord).ThenBy(frame => frame.SourceFrame).ToArray(),
    };

    private static NormalizedMediaManifest CanonicalizeMedia(NormalizedMediaManifest manifest)
    {
        ArgumentNullException.ThrowIfNull(manifest);
        ArgumentNullException.ThrowIfNull(manifest.Resources);
        return new(manifest.Resources
            .OrderBy(resource => resource.Id, StringComparer.Ordinal)
            .Select(resource => resource with
            {
                Frames = resource.Frames.OrderBy(frame => frame.FrameIndex).ThenBy(frame => frame.Id, StringComparer.Ordinal).ToArray(),
                Sequence = resource.Sequence?.ToArray(),
            })
            .ToArray());
    }

    private static byte[] SerializeSidecar<T>(T sidecar)
    {
        byte[] bytes = JsonSerializer.SerializeToUtf8Bytes(sidecar, JsonOptions);
        return [.. bytes, (byte)'\n'];
    }

    private static void ValidateDungeonMedia(Arena2DungeonMediaPublication publication)
    {
        ArgumentNullException.ThrowIfNull(publication.Artifacts);
        ArgumentNullException.ThrowIfNull(publication.MaterialTextures);
        ArgumentNullException.ThrowIfNull(publication.Billboards);
        ArgumentNullException.ThrowIfNull(publication.Actors);
        ValidateArtifacts(publication.Artifacts, "dungeon media");
        IReadOnlyDictionary<string, NormalizedMediaDescriptor> media = ValidateMediaManifest(publication.MediaManifest, publication.Artifacts, "dungeon media");

        foreach (DungeonMaterialTextureMedia material in publication.MaterialTextures)
        {
            ArgumentNullException.ThrowIfNull(material);
            NormalizedImportDocument.RequireLogicalId(material.TextureResourceId, nameof(material.TextureResourceId));
            NormalizedImportDocument.RequireLogicalId(material.MaterialResourceId, nameof(material.MaterialResourceId));
            NormalizedMediaDescriptor descriptor = RequireCanonicalDescriptor(media, material.Descriptor, material.Descriptor.Id, "dungeon material");
            if (descriptor.Kind != NormalizedMediaKind.Texture
                || material.Width <= 0 || material.Height <= 0
                || descriptor.SourceWidth != material.Width || descriptor.SourceHeight != material.Height
                || !ArtifactMatchesDescriptor(material.Artifact, descriptor))
            {
                throw new InvalidOperationException("Dungeon material metadata must identify one canonical, positive-size texture descriptor.");
            }
        }

        foreach (DungeonBillboardSpriteMedia billboard in publication.Billboards)
        {
            ArgumentNullException.ThrowIfNull(billboard);
            ValidateSpriteReference(
                billboard.SpriteResourceId,
                billboard.Descriptor,
                billboard.Artifact,
                media,
                billboard.Frames,
                billboard.Pivot,
                billboard.WorldSize,
                billboard.Playback,
                "dungeon billboard");
            billboard.SourcePlayback?.Validate();
        }

        foreach (DungeonActorSpriteMedia actor in publication.Actors)
        {
            ArgumentNullException.ThrowIfNull(actor);
            NormalizedImportDocument.RequireLogicalId(actor.ActorResourceId, nameof(actor.ActorResourceId));
            if (string.IsNullOrWhiteSpace(actor.SourceName) || actor.States.Count == 0)
            {
                throw new InvalidOperationException("Dungeon actor media requires a source name and at least one source-state layout.");
            }

            actor.SourceAttackSequence.Validate();
            ValidateSpriteReference(
                actor.SpriteResourceId,
                actor.Descriptor,
                actor.Artifact,
                media,
                actor.States.SelectMany(state => state.Frames).ToArray(),
                actor.Pivot,
                actor.WorldSize,
                null,
                "dungeon actor",
                requireDescriptorPlayback: false);
            actor.SourceWorldSize.Validate(nameof(actor.SourceWorldSize));
            if (actor.SourceWorldSize.X <= 0F || actor.SourceWorldSize.Y <= 0F)
            {
                throw new InvalidOperationException("Dungeon actor source world size must be positive.");
            }

            if (actor.States.Select(state => state.State).Distinct().Count() != actor.States.Count)
            {
                throw new InvalidOperationException("Dungeon actor media contains duplicate source states.");
            }

            if (!Enum.IsDefined(actor.PreferredRestState)
                || !actor.States.Any(state => state.State == actor.PreferredRestState))
            {
                throw new InvalidOperationException("Dungeon actor media must publish its declared preferred rest state.");
            }

            foreach (DungeonActorSpriteStateLayout state in actor.States)
            {
                state.Validate();
                ValidateStateRange(state);
                if ((actor.Descriptor.FramesPerSecond is not null && state.Playback.FramesPerSecond != actor.Descriptor.FramesPerSecond)
                    || (actor.Descriptor.Loop is not null && state.Playback.Loops != actor.Descriptor.Loop))
                {
                    throw new InvalidOperationException("Dungeon actor state playback must agree with the canonical media descriptor.");
                }
            }

            if (actor.Corpse is not null)
            {
                ValidateSpriteReference(
                    actor.Corpse.Descriptor.Id,
                    actor.Corpse.Descriptor,
                    actor.Corpse.Artifact,
                    media,
                    [actor.Corpse.Frame],
                    actor.Corpse.Pivot,
                    actor.Corpse.WorldSize,
                    null,
                    "dungeon corpse");
                actor.Corpse.SourceWorldSize.Validate(nameof(actor.Corpse.SourceWorldSize));
                if (actor.Corpse.SourceWorldSize.X <= 0F || actor.Corpse.SourceWorldSize.Y <= 0F)
                {
                    throw new InvalidOperationException("Dungeon corpse source world size must be positive.");
                }
            }
        }
    }

    private static void ValidateClassicMedia(Arena2ClassicMediaPublication publication)
    {
        ArgumentNullException.ThrowIfNull(publication.Artifacts);
        ArgumentNullException.ThrowIfNull(publication.Sources);
        ArgumentNullException.ThrowIfNull(publication.WeaponActions);
        ArgumentNullException.ThrowIfNull(publication.Effects);
        ArgumentNullException.ThrowIfNull(publication.Audio);
        ArgumentNullException.ThrowIfNull(publication.UiImages);
        ArgumentNullException.ThrowIfNull(publication.InventoryIcons);
        ValidateArtifacts(publication.Artifacts, "classic media");
        IReadOnlyDictionary<string, NormalizedMediaDescriptor> media = ValidateMediaManifest(publication.MediaManifest, publication.Artifacts, "classic media");
        foreach (LogicalSourceRecord source in publication.Sources)
        {
            source.Validate();
        }
        NormalizedImportDocument.ValidateUnique(publication.Sources, source => source.SourcePath, "classic media logical source");

        NormalizedMediaDescriptor weapon = media.Values.SingleOrDefault(resource => resource.Kind == NormalizedMediaKind.WeaponSprite)
            ?? throw new InvalidOperationException("Classic media must contain exactly one canonical weapon sprite descriptor.");
        if (media.Values.Count(resource => resource.Kind == NormalizedMediaKind.WeaponSprite) != 1)
        {
            throw new InvalidOperationException("Classic media contains more than one weapon sprite descriptor.");
        }

        ClassicDaggerWeaponAction[] expectedWeaponActions = Enum.GetValues<ClassicDaggerWeaponAction>();
        if (publication.WeaponActions.Count != expectedWeaponActions.Length
            || !publication.WeaponActions.Select(action => action.Action).SequenceEqual(expectedWeaponActions))
        {
            throw new InvalidOperationException("Classic weapon metadata must contain the exact fixed dagger action set.");
        }

        HashSet<int> coveredWeaponFrames = [];
        int expectedWeaponFrameStart = 0;
        foreach (ClassicWeaponActionManifest action in publication.WeaponActions)
        {
            try
            {
                action.Validate(weapon.Frames.Count);
            }
            catch (ArgumentException exception)
            {
                throw new InvalidOperationException("Classic weapon metadata is invalid.", exception);
            }

            if (action.FrameStart != expectedWeaponFrameStart)
            {
                throw new InvalidOperationException("Classic weapon action ranges must retain canonical action order.");
            }

            if (action.SourceRecordOrdinal != ExpectedWeaponActionSourceRecordOrdinal(action.Action))
            {
                throw new InvalidOperationException("Classic weapon action source records must retain their fixed Daggerfall positions.");
            }

            for (int frame = action.FrameStart; frame < action.FrameStart + action.FrameCount; frame++)
            {
                if (!coveredWeaponFrames.Add(frame))
                {
                    throw new InvalidOperationException("Classic weapon action ranges overlap in the canonical weapon descriptor.");
                }
            }

            expectedWeaponFrameStart = checked(expectedWeaponFrameStart + action.FrameCount);
        }

        if (!coveredWeaponFrames.SetEquals(weapon.Frames.Select(frame => frame.FrameIndex)))
        {
            throw new InvalidOperationException("Classic weapon actions must uniquely cover every canonical weapon frame.");
        }

        ValidateEffectProjections(publication.Effects, media);
        ValidateClassicReferences(publication.Audio.Select(audio => audio.MediaId), media, NormalizedMediaKind.Audio, "audio");
        ValidateClassicReferences(publication.UiImages.Select(image => image.MediaId), media, NormalizedMediaKind.UserInterface, "UI image");
        ValidateClassicReferences(publication.InventoryIcons.Select(icon => icon.MediaId), media, NormalizedMediaKind.UserInterface, "inventory icon");
        ArgumentNullException.ThrowIfNull(publication.Font);
        ValidateClassicReferences([publication.Font.MediaId], media, NormalizedMediaKind.Font, "font");
        if (publication.Font.FixedWidth is 0 or > 16 || publication.Font.FixedHeight is 0 or > 16 || publication.Font.Glyphs is null || publication.Font.Glyphs.Count != Arena2FormatConstants.FntGlyphCount
            || publication.Font.Glyphs.Select(glyph => glyph.GlyphIndex).Distinct().Count() != publication.Font.Glyphs.Count
            || publication.Font.Glyphs.Any(glyph => glyph.GlyphIndex < 0 || glyph.GlyphIndex >= Arena2FormatConstants.FntGlyphCount || glyph.X < 0 || glyph.Y < 0 || glyph.Advance > 16))
        {
            throw new InvalidOperationException("Classic font metadata is invalid.");
        }

        ArgumentNullException.ThrowIfNull(publication.AuthoredUiAssets);
        NormalizedImportDocument.ValidateUnique(publication.AuthoredUiAssets, asset => asset.Id, "authored UI media");
        NormalizedImportDocument.ValidateUnique(publication.AuthoredUiAssets, asset => asset.RelativePath, "authored UI path");
        foreach (ClassicAuthoredUiAssetManifest asset in publication.AuthoredUiAssets)
        {
            NormalizedImportDocument.RequireLogicalId(asset.Id, nameof(asset.Id));
            NormalizedImportDocument.RequireLogicalPath(asset.RelativePath, nameof(asset.RelativePath));
            NormalizedImportDocument.RequireLogicalPath(asset.SourceLabel, nameof(asset.SourceLabel));
            if (string.IsNullOrWhiteSpace(asset.Generator) || string.IsNullOrWhiteSpace(asset.Prompt)
                || !media.TryGetValue(asset.Id, out NormalizedMediaDescriptor? descriptor)
                || descriptor.Kind != NormalizedMediaKind.UserInterface
                || !StringComparer.Ordinal.Equals(descriptor.RelativePath, asset.RelativePath)
                || !publication.Sources.Any(source => StringComparer.Ordinal.Equals(source.SourcePath, $"authored-ui/{asset.SourceLabel}")))
            {
                throw new InvalidOperationException("Classic authored UI metadata must agree with a canonical UI descriptor and retained provenance.");
            }
        }

        if (publication.AuthoredUiManifestSource is not null
            && !publication.Sources.Contains(publication.AuthoredUiManifestSource))
        {
            throw new InvalidOperationException("Classic authored UI manifest provenance must be retained by the publication source set.");
        }
    }

    private static void ValidateArtifacts(IReadOnlyList<ImportPublicationArtifact> artifacts, string family)
    {
        if (artifacts.Count == 0 || artifacts.Any(artifact => artifact is null))
        {
            throw new InvalidOperationException($"{family} must emit at least one artifact.");
        }

        if (artifacts.Select(artifact => artifact.RelativePath).Distinct(StringComparer.Ordinal).Count() != artifacts.Count)
        {
            throw new InvalidOperationException($"{family} contains duplicate artifact paths.");
        }
    }

    private static IReadOnlyDictionary<string, NormalizedMediaDescriptor> ValidateMediaManifest(
        NormalizedMediaManifest manifest,
        IReadOnlyList<ImportPublicationArtifact> artifacts,
        string family)
    {
        ArgumentNullException.ThrowIfNull(manifest);
        ArgumentNullException.ThrowIfNull(manifest.Resources);
        if (manifest.Resources.Count == 0 || manifest.Resources.Any(resource => resource is null)
            || manifest.Resources.Select(resource => resource.Id).Distinct(StringComparer.Ordinal).Count() != manifest.Resources.Count
            || manifest.Resources.Select(resource => resource.RelativePath).Distinct(StringComparer.Ordinal).Count() != manifest.Resources.Count)
        {
            throw new InvalidOperationException($"{family} media metadata must have unique resources.");
        }

        Dictionary<string, ImportPublicationArtifact> artifactsByPath = artifacts.ToDictionary(artifact => artifact.RelativePath, StringComparer.Ordinal);
        foreach (NormalizedMediaDescriptor resource in manifest.Resources)
        {
            NormalizedImportDocument.RequireLogicalId(resource.Id, nameof(resource.Id));
            NormalizedImportDocument.RequireLogicalPath(resource.RelativePath, nameof(resource.RelativePath));
            resource.ContentDigest.Validate();
            if (!Enum.IsDefined(resource.Kind) || resource.ByteLength <= 0 || string.IsNullOrWhiteSpace(resource.MimeType)
                || resource.SourceWidth < 0 || resource.SourceHeight < 0 || resource.AtlasWidth < 0 || resource.AtlasHeight < 0
                || resource.Frames is null || !artifactsByPath.TryGetValue(resource.RelativePath, out ImportPublicationArtifact? artifact)
                || artifact.ContentHash != resource.ContentDigest || artifact.Bytes.Length != resource.ByteLength)
            {
                throw new InvalidOperationException($"{family} media descriptor '{resource.Id}' does not match one emitted artifact.");
            }

            if (resource.Frames.Count == 0 && (resource.AtlasWidth != 0 || resource.AtlasHeight != 0))
            {
                throw new InvalidOperationException($"{family} media descriptor '{resource.Id}' has atlas dimensions without regenerated frames.");
            }

            if (resource.Frames.Count != 0 && (resource.AtlasWidth <= 0 || resource.AtlasHeight <= 0))
            {
                throw new InvalidOperationException($"{family} media descriptor '{resource.Id}' has regenerated frames without positive atlas dimensions.");
            }

            if (resource.Frames.Select(frame => frame.Id).Distinct(StringComparer.Ordinal).Count() != resource.Frames.Count
                || resource.Frames.Select(frame => frame.FrameIndex).Distinct().Count() != resource.Frames.Count
                || resource.Frames.OrderBy(frame => frame.FrameIndex).Select((frame, index) => frame.FrameIndex != index).Any(value => value)
                || resource.Frames.Any(frame => string.IsNullOrWhiteSpace(frame.Id) || frame.FrameIndex < 0 || frame.X < 0 || frame.Y < 0 || frame.Width <= 0 || frame.Height <= 0 || frame.SourceWidth <= 0 || frame.SourceHeight <= 0
                    || (long)frame.X + frame.Width > resource.AtlasWidth || (long)frame.Y + frame.Height > resource.AtlasHeight))
            {
                throw new InvalidOperationException($"{family} media descriptor '{resource.Id}' has invalid regenerated frame metadata.");
            }

            resource.Pivot?.Validate(nameof(resource.Pivot));
            resource.DisplaySize?.Validate(nameof(resource.DisplaySize));
            if (resource.DisplaySize is { X: <= 0F } or { Y: <= 0F }
                || resource.FramesPerSecond is <= 0F
                || (resource.FramesPerSecond is not null && !float.IsFinite(resource.FramesPerSecond.Value))
                || resource.Sequence is { Count: 0 }
                || resource.Sequence?.Any(index => index < 0 || index >= resource.Frames.Count) == true)
            {
                throw new InvalidOperationException($"{family} media descriptor '{resource.Id}' has invalid authored metadata.");
            }
        }

        return manifest.Resources.ToDictionary(resource => resource.Id, StringComparer.Ordinal);
    }

    private static void ValidateSpriteReference(
        string expectedId,
        NormalizedMediaDescriptor descriptor,
        ImportPublicationArtifact artifact,
        IReadOnlyDictionary<string, NormalizedMediaDescriptor> media,
        IReadOnlyList<DungeonMediaFrameLayout> frames,
        NormalizedVector2 pivot,
        NormalizedVector2? worldSize,
        DungeonSpritePlaybackSource? playback,
        string family,
        bool requireDescriptorPlayback = true)
    {
        NormalizedImportDocument.RequireLogicalId(expectedId, nameof(expectedId));
        NormalizedMediaDescriptor canonical = RequireCanonicalDescriptor(media, descriptor, expectedId, family);
        if (!ArtifactMatchesDescriptor(artifact, canonical) || frames.Count == 0)
        {
            throw new InvalidOperationException($"{family} metadata must identify one canonical generated sprite descriptor with frames.");
        }

        pivot.Validate(nameof(pivot));
        worldSize?.Validate(nameof(worldSize));
        if (worldSize is { X: <= 0F } or { Y: <= 0F })
        {
            throw new InvalidOperationException("Dungeon sprite world size must be positive.");
        }

        if (canonical.Pivot is not null && canonical.Pivot != pivot
            || canonical.DisplaySize is not null && canonical.DisplaySize != worldSize
            || requireDescriptorPlayback && canonical.FramesPerSecond is not null && (playback is null || playback.FramesPerSecond != canonical.FramesPerSecond)
            || requireDescriptorPlayback && canonical.Loop is not null && (playback is null || playback.Loops != canonical.Loop))
        {
            throw new InvalidOperationException($"{family} effective presentation does not agree with its canonical media descriptor.");
        }

        ValidateFrameLayouts(canonical, frames, family);
    }

    private static void ValidateStateRange(DungeonActorSpriteStateLayout state)
    {
        int expectedCount = checked(8 * state.FramesPerOrientation);
        IReadOnlyList<int> expected = Enumerable.Range(state.FrameStart, expectedCount).ToArray();
        IReadOnlyList<int> actual = state.Frames.OrderBy(frame => frame.AtlasFrameIndex).Select(frame => frame.AtlasFrameIndex).ToArray();
        if (!actual.SequenceEqual(expected))
        {
            throw new InvalidOperationException("Dungeon actor state layout does not match its declared contiguous canonical frame range.");
        }
    }

    private static void ValidateFrameLayouts(NormalizedMediaDescriptor descriptor, IReadOnlyList<DungeonMediaFrameLayout> layouts, string family)
    {
        if (layouts.Select(layout => layout.AtlasFrameIndex).Distinct().Count() != layouts.Count
            || layouts.Count != descriptor.Frames.Count)
        {
            throw new InvalidOperationException($"{family} frame layouts must uniquely cover the canonical descriptor frames.");
        }

        Dictionary<int, NormalizedAtlasFrame> byIndex = descriptor.Frames.ToDictionary(frame => frame.FrameIndex);
        foreach (DungeonMediaFrameLayout layout in layouts)
        {
            layout.Validate();
            if (!byIndex.TryGetValue(layout.AtlasFrameIndex, out NormalizedAtlasFrame? canonical) || canonical != layout.AtlasFrame)
            {
                throw new InvalidOperationException($"{family} frame layout does not match its canonical descriptor atlas frame.");
            }
        }
    }

    private static NormalizedMediaDescriptor RequireCanonicalDescriptor(
        IReadOnlyDictionary<string, NormalizedMediaDescriptor> media,
        NormalizedMediaDescriptor descriptor,
        string expectedId,
        string family)
    {
        ArgumentNullException.ThrowIfNull(descriptor);
        if (!media.TryGetValue(expectedId, out NormalizedMediaDescriptor? canonical)
            || !DescriptorMatchesCanonical(descriptor, canonical))
        {
            throw new InvalidOperationException($"{family} projection must use the canonical media descriptor '{expectedId}'.");
        }

        return canonical;
    }

    private static bool DescriptorMatchesCanonical(NormalizedMediaDescriptor candidate, NormalizedMediaDescriptor canonical) =>
        StringComparer.Ordinal.Equals(candidate.Id, canonical.Id)
        && candidate.Kind == canonical.Kind
        && StringComparer.Ordinal.Equals(candidate.RelativePath, canonical.RelativePath)
        && candidate.ContentDigest == canonical.ContentDigest
        && candidate.ByteLength == canonical.ByteLength
        && StringComparer.Ordinal.Equals(candidate.MimeType, canonical.MimeType)
        && candidate.SourceWidth == canonical.SourceWidth
        && candidate.SourceHeight == canonical.SourceHeight
        && candidate.AtlasWidth == canonical.AtlasWidth
        && candidate.AtlasHeight == canonical.AtlasHeight
        && candidate.Frames.SequenceEqual(canonical.Frames)
        && StringComparer.Ordinal.Equals(candidate.DisplayName, canonical.DisplayName)
        && candidate.Pivot == canonical.Pivot
        && candidate.DisplaySize == canonical.DisplaySize
        && candidate.FramesPerSecond == canonical.FramesPerSecond
        && candidate.Loop == canonical.Loop
        && SequenceEqual(candidate.Sequence, canonical.Sequence);

    private static bool ArtifactMatchesDescriptor(ImportPublicationArtifact artifact, NormalizedMediaDescriptor descriptor) =>
        StringComparer.Ordinal.Equals(artifact.RelativePath, descriptor.RelativePath)
        && artifact.ContentHash == descriptor.ContentDigest
        && artifact.Bytes.Length == descriptor.ByteLength;

    private static bool SequenceEqual<T>(IReadOnlyList<T>? left, IReadOnlyList<T>? right) =>
        left is null ? right is null : right is not null && left.SequenceEqual(right);

    private static void ValidateClassicReferences(
        IEnumerable<string> mediaIds,
        IReadOnlyDictionary<string, NormalizedMediaDescriptor> media,
        NormalizedMediaKind expectedKind,
        string family)
    {
        foreach (string mediaId in mediaIds)
        {
            NormalizedImportDocument.RequireLogicalId(mediaId, nameof(mediaIds));
            if (!media.TryGetValue(mediaId, out NormalizedMediaDescriptor? descriptor) || descriptor.Kind != expectedKind)
            {
                throw new InvalidOperationException($"Classic {family} metadata identifies an unknown or incompatible canonical media resource '{mediaId}'.");
            }
        }
    }

    private static void ValidateEffectProjections(
        IReadOnlyList<ClassicEffectManifest> effects,
        IReadOnlyDictionary<string, NormalizedMediaDescriptor> media)
    {
        ArgumentNullException.ThrowIfNull(effects);
        ClassicEffect[] expectedEffects = Enum.GetValues<ClassicEffect>();
        if (effects.Count != expectedEffects.Length
            || !effects.Select(effect => effect.Effect).Order().SequenceEqual(expectedEffects))
        {
            throw new InvalidOperationException("Classic effect metadata must contain the exact selected effect set.");
        }

        foreach (ClassicEffectManifest effect in effects)
        {
            try
            {
                effect.Validate();
            }
            catch (ArgumentException exception)
            {
                throw new InvalidOperationException("Classic effect metadata is invalid.", exception);
            }

            if (effect.SourceRecordOrdinal != Arena2ClassicMediaPublication.ExpectedEffectSourceRecordOrdinal(effect.Effect))
            {
                throw new InvalidOperationException("Classic effect metadata must retain its fixed TEXTURE.380 source record.");
            }

            if (!media.TryGetValue(effect.MediaId, out NormalizedMediaDescriptor? descriptor)
                || descriptor.Kind != NormalizedMediaKind.EffectSprite
                || descriptor.Frames.Count == 0
                || descriptor.FramesPerSecond != effect.Timing.FramesPerSecond
                || descriptor.Loop != effect.Timing.Loop)
            {
                throw new InvalidOperationException("Classic effect timing and loop settings must agree with their canonical media descriptor.");
            }

            // Sequence is an authored descriptor value with no duplicate
            // effect-manifest field. ValidateMediaManifest has already proved
            // that any present sequence refers only to this descriptor's
            // regenerated frame indexes.
        }
    }
}
