interface ProjectionEnvelope { readonly contract: string; readonly value: unknown; }
interface ProductUiContext { readonly projection?: { subscribe(listener: (projection: ProjectionEnvelope | null) => void): () => void }; readonly intents?: { claim(intent: string, value: { kind: 'product-payload'; contract: string; data: Record<string, unknown> }): void }; }
interface SpriteRow { readonly id: string; readonly label: string; readonly kind: string; readonly frameCount: number; readonly stateCount: number; readonly actionCount: number; }
interface Sequence { readonly name: string; readonly orientation: number; readonly frameIds: readonly number[]; }
interface SequenceFrameOption { readonly sequenceIndex: number; readonly frameId: number; }
interface Overlay { readonly displayName: string | null; readonly pivotX: number | null; readonly pivotY: number | null; readonly displaySizeX: number | null; readonly displaySizeY: number | null; readonly fps: number | null; readonly loop: number | null; readonly frameSequence: readonly number[]; }
interface Selected { readonly id: string; readonly provenance: { readonly path: string; readonly digest: string; readonly byteLength: number; readonly dependsOnPaths: readonly string[]; readonly sources: readonly Record<string, unknown>[] }; readonly atlas: { readonly width: number; readonly height: number }; readonly frames: readonly Record<string, unknown>[]; readonly states: readonly Record<string, unknown>[]; readonly actions: readonly Record<string, unknown>[]; readonly availableSequences: readonly Sequence[]; readonly availableOrientations: readonly number[]; readonly availableSequenceFrames: readonly SequenceFrameOption[]; readonly authored: Overlay; readonly saved: Overlay | null; readonly pending: Overlay | null; readonly playback: { readonly state: string; readonly frameIndex: number; readonly frameId: number; readonly cycle: number } | null; }
interface SpriteProjection { readonly entries: readonly SpriteRow[]; readonly selectedId: string | null; readonly selectedSequence: string | null; readonly selectedOrientation: number; readonly playing: number; readonly frameIndex: number | null; readonly frameId: number | null; readonly cycle: number | null; readonly diagnostic: string | null; readonly saveStatus: string; readonly selected: Selected | null; }
const contract = 'worldrpg.sprite-workbench.snapshot.v1';
const payloadContract = 'worldrpg.sprite-workbench.intent.v1';

/** Engine-hosted product UI: it only renders projections and emits semantic product payloads. */
export function mountProductUi(root: HTMLElement, context: ProductUiContext): { dispose(): void } {
  let projection: SpriteProjection | null = null; let filter = '';
  const claim = (action: string, extra: Record<string, unknown> = {}): void => context.intents?.claim('sprite-workbench', { kind: 'product-payload', contract: payloadContract, data: { action, ...extra } });
  const button = (label: string, onClick: () => void): HTMLButtonElement => { const value = document.createElement('button'); value.type = 'button'; value.textContent = label; value.addEventListener('click', onClick); return value; };
  const select = (values: readonly string[], value: string | null, onChange: (value: string) => void): HTMLSelectElement => { const input = document.createElement('select'); for (const item of values) { const option = document.createElement('option'); option.value = item; option.textContent = item; option.selected = item === value; input.append(option); } input.addEventListener('change', () => onChange(input.value)); return input; };
  const selectSequenceFrame = (id: string, values: readonly SequenceFrameOption[], selectedIndex: number | null): HTMLSelectElement => { const input = document.createElement('select'); for (const item of values) { const option = document.createElement('option'); option.value = String(item.sequenceIndex); option.textContent = `entry ${item.sequenceIndex}: frame ${item.frameId}`; option.selected = item.sequenceIndex === selectedIndex; input.append(option); } input.addEventListener('change', () => { const selected = values.find(item => item.sequenceIndex === Number(input.value)); if (selected !== undefined) claim('select-frame', { id, sequenceFrameIndex: selected.sequenceIndex }); }); return input; };
  const render = (): void => {
    root.replaceChildren(); const search = document.createElement('input'); search.placeholder = 'Filter sprites'; search.value = filter; search.addEventListener('input', () => { filter = search.value; render(); }); root.append(search);
    if (projection === null) { root.append(document.createTextNode('Awaiting sprite workbench projection…')); return; }
    const list = document.createElement('nav');
    const groups = new Map<string, SpriteRow[]>(); for (const entry of projection.entries.filter(value => `${value.label} ${value.kind}`.toLowerCase().includes(filter.toLowerCase()))) groups.set(entry.kind, [...(groups.get(entry.kind) ?? []), entry]);
    for (const [kind, entries] of groups) { const heading = document.createElement('h3'); heading.textContent = kind; list.append(heading); for (const entry of entries) list.append(button(entry.label, () => claim('select', { id: entry.id, orientation: 0 }))); }
    root.append(list);
    const current = projection; const selected = current.selected;
    if (selected !== null && current.selectedId !== null) {
      const id = current.selectedId; const panel = document.createElement('section');
      panel.append(document.createTextNode(`source ${selected.provenance.path}; ${selected.provenance.digest}; ${selected.provenance.byteLength} bytes; atlas ${selected.atlas.width} x ${selected.atlas.height}`));
      panel.append(select(selected.availableSequences.map(value => value.name), current.selectedSequence, sequence => { const found = selected.availableSequences.find(value => value.name === sequence); claim('select', { id, sequence, orientation: found?.orientation ?? 0 }); }));
      panel.append(select(selected.availableOrientations.map(String), String(current.selectedOrientation), orientation => claim('select', { id, sequence: current.selectedSequence, orientation: Number(orientation) })));
      panel.append(selectSequenceFrame(id, selected.availableSequenceFrames, current.frameIndex));
      for (const action of ['play', 'pause', 'resume', 'restart', 'stop', 'step'] as const) panel.append(button(action, () => claim(action, { id })));
      const elapsed = document.createElement('input'); elapsed.type = 'number'; elapsed.min = '0'; elapsed.max = '3600'; elapsed.step = '0.001'; elapsed.value = '0'; panel.append(elapsed, button('sample', () => { const seconds = Number(elapsed.value); if (Number.isFinite(seconds) && seconds >= 0 && seconds <= 3600) claim('sample', { id, elapsedSeconds: seconds }); }));
      const inspect = (heading: string, value: unknown): void => { const section = document.createElement('details'); const title = document.createElement('summary'); title.textContent = heading; const facts = document.createElement('pre'); facts.textContent = JSON.stringify(value, null, 2); section.append(title, facts); panel.append(section); };
      inspect('Provenance dependencies', selected.provenance.dependsOnPaths); inspect('Publication sources', selected.provenance.sources); inspect('Frames: atlas rectangles and source/orientation facts', selected.frames); inspect('States: timing, loop, preferred rest, frames', selected.states); inspect('Actions: timing, membership, source ordinal and damage markers', selected.actions); inspect('Authored values', selected.authored); inspect('Saved values', selected.saved); inspect('Pending values', selected.pending); inspect('Engine playback readout', selected.playback);
      const edit = document.createElement('fieldset'); edit.append(document.createTextNode('Authored overlay'));
      const values = selected.pending ?? selected.saved ?? selected.authored;
      const fields: Array<[string, keyof Overlay]> = [['Display name', 'displayName'], ['Pivot X', 'pivotX'], ['Pivot Y', 'pivotY'], ['Display size X', 'displaySizeX'], ['Display size Y', 'displaySizeY'], ['FPS', 'fps'], ['Loop (0 or 1)', 'loop'], ['Sequence (comma separated)', 'frameSequence']];
      const inputs = new Map<keyof Overlay, HTMLInputElement>();
      for (const [label, key] of fields) { const input = document.createElement('input'); input.placeholder = label; const value = values[key]; input.value = Array.isArray(value) ? value.join(',') : value === null ? '' : String(value); inputs.set(key, input); const caption = document.createElement('label'); caption.textContent = label; caption.append(input); edit.append(caption); }
      edit.append(button('Apply edit', () => { const text = (key: keyof Overlay): string | null => { const value = inputs.get(key)!.value.trim(); return value === '' ? null : value; }; const number = (key: keyof Overlay): number | null => { const value = text(key); return value === null ? null : Number(value); }; const sequence = text('frameSequence'); claim('edit', { id, displayName: text('displayName'), pivotX: number('pivotX'), pivotY: number('pivotY'), displaySizeX: number('displaySizeX'), displaySizeY: number('displaySizeY'), framesPerSecond: number('fps'), loop: number('loop') === null ? null : number('loop') === 1, frameSequence: sequence === null ? null : sequence.split(',').map(value => Number(value.trim())) }); }));
      edit.append(button('Save', () => claim('save', { id }))); edit.append(button('Discard unsaved', () => claim('discard', { id }))); panel.append(edit); root.append(panel);
    }
    const status = document.createElement('output'); status.textContent = `${projection.saveStatus}${projection.diagnostic === null ? '' : `: ${projection.diagnostic}`}`; root.append(status);
  };
  const unsubscribe = context.projection?.subscribe(envelope => { if (envelope?.contract === contract && isProjection(envelope.value)) { projection = envelope.value; render(); } }) ?? (() => {});
  render(); return { dispose: () => unsubscribe() };
}

export function isProjection(value: unknown): value is SpriteProjection {
  if (!object(value) || !Array.isArray(value.entries) || !value.entries.every(isRow)) return false;
  return nullableString(value.selectedId) && nullableString(value.selectedSequence) && finite(value.selectedOrientation) && finite(value.playing) && nullableNumber(value.frameIndex) && nullableNumber(value.frameId) && nullableNumber(value.cycle) && nullableString(value.diagnostic) && string(value.saveStatus) && nullableSelected(value.selected);
}
function nullableSelected(value: unknown): value is Selected | null { return value === null || (object(value) && string(value.id) && object(value.provenance) && string(value.provenance.path) && string(value.provenance.digest) && finite(value.provenance.byteLength) && Array.isArray(value.provenance.dependsOnPaths) && value.provenance.dependsOnPaths.every(string) && Array.isArray(value.provenance.sources) && value.provenance.sources.every(object) && object(value.atlas) && finite(value.atlas.width) && finite(value.atlas.height) && Array.isArray(value.frames) && value.frames.every(object) && Array.isArray(value.states) && value.states.every(object) && Array.isArray(value.actions) && value.actions.every(object) && Array.isArray(value.availableSequences) && value.availableSequences.every(sequence) && Array.isArray(value.availableOrientations) && value.availableOrientations.every(finite) && Array.isArray(value.availableSequenceFrames) && value.availableSequenceFrames.every(sequenceFrameOption) && overlay(value.authored) && (value.saved === null || overlay(value.saved)) && (value.pending === null || overlay(value.pending)) && (value.playback === null || playback(value.playback))); }
function sequence(value: unknown): value is Sequence { return object(value) && string(value.name) && finite(value.orientation) && Array.isArray(value.frameIds) && value.frameIds.every(finite); }
function sequenceFrameOption(value: unknown): value is SequenceFrameOption { return object(value) && finite(value.sequenceIndex) && finite(value.frameId); }
function overlay(value: unknown): value is Overlay { return object(value) && nullableString(value.displayName) && nullableNumber(value.pivotX) && nullableNumber(value.pivotY) && nullableNumber(value.displaySizeX) && nullableNumber(value.displaySizeY) && nullableNumber(value.fps) && nullableNumber(value.loop) && Array.isArray(value.frameSequence) && value.frameSequence.every(finite); }
function playback(value: unknown): boolean { return object(value) && string(value.state) && finite(value.frameIndex) && finite(value.frameId) && finite(value.cycle); }
function isRow(value: unknown): value is SpriteRow { return object(value) && string(value.id) && string(value.label) && string(value.kind) && finite(value.frameCount) && finite(value.stateCount) && finite(value.actionCount); }
function object(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null; }
function string(value: unknown): value is string { return typeof value === 'string'; }
function finite(value: unknown): value is number { return typeof value === 'number' && Number.isFinite(value); }
function nullableString(value: unknown): value is string | null { return value === null || string(value); }
function nullableNumber(value: unknown): value is number | null { return value === null || finite(value); }
