using System.Text.Json;
using System.Text.Json.Serialization;

namespace WorldRpg.SpriteAuthoring;

/// <summary>Dedicated tracked input for future source regeneration; it is not a generated sidecar.</summary>
public sealed record SpriteAuthoredOverlayDocument(int SchemaVersion, SpriteContentDigest AuthoringBasisDigest, IReadOnlyList<SpriteAuthoredOverlay> Overlays)
{
    public const int CurrentSchemaVersion = 1;
}

/// <summary>Typed authored overlay values. Generated bytes, paths, hashes, and source facts have no fields here.</summary>
public sealed record SpriteAuthoredFrameRect(int FrameIndex, int X, int Y, int Width, int Height);

public sealed record SpriteAuthoredStateTiming(string Name, float? FramesPerSecond = null, bool? Loop = null);

public sealed record SpriteAuthoredActionTiming(string Name, float? FramesPerSecond = null, bool? Loop = null);

public sealed record SpriteAuthoredOverlay(
    string Id,
    string? DisplayName = null,
    SpriteVector2? Pivot = null,
    SpriteVector2? DisplaySize = null,
    float? FramesPerSecond = null,
    bool? Loop = null,
    IReadOnlyList<int>? Sequence = null,
    IReadOnlyList<SpriteAuthoredFrameRect>? FrameRects = null,
    IReadOnlyList<SpriteAuthoredStateTiming>? StateTimings = null,
    IReadOnlyList<SpriteAuthoredActionTiming>? ActionTimings = null);

/// <summary>Applies saved authored values to an inspection projection without changing generated bytes or source facts.</summary>
public static class SpriteAuthoredOverlayApplicator
{
    public static SpriteInspectionEntry Apply(SpriteInspectionEntry entry, SpriteAuthoredOverlay overlay)
    {
        ArgumentNullException.ThrowIfNull(entry);
        ArgumentNullException.ThrowIfNull(overlay);
        if (!StringComparer.Ordinal.Equals(entry.Id, overlay.Id))
        {
            throw new ArgumentException("An authored overlay must identify the inspected sprite entry.", nameof(overlay));
        }

        SpriteAuthoredOverlayStore.ValidateValues(overlay, entry);
        SpriteAuthoredValues values = entry.AuthoredValues;
        return entry with
        {
            Label = overlay.DisplayName ?? entry.Label,
            AuthoredValues = new(
                overlay.DisplayName ?? values.DisplayName,
                overlay.Pivot ?? values.Pivot,
                overlay.DisplaySize ?? values.DisplaySize,
                overlay.FramesPerSecond ?? values.FramesPerSecond,
                overlay.Loop ?? values.Loop,
                overlay.Sequence ?? values.Sequence),
            Frames = entry.Frames.Select(frame => overlay.FrameRects?.SingleOrDefault(rect => rect.FrameIndex == frame.FrameIndex) is { } rect
                ? frame with { X = rect.X, Y = rect.Y, Width = rect.Width, Height = rect.Height }
                : frame).ToArray(),
            States = entry.States.Select(state =>
            {
                SpriteAuthoredStateTiming? timing = overlay.StateTimings?.SingleOrDefault(value => StringComparer.Ordinal.Equals(value.Name, state.Name));
                return state with
                {
                    FramesPerSecond = timing?.FramesPerSecond ?? overlay.FramesPerSecond ?? state.FramesPerSecond,
                    Loops = timing?.Loop ?? overlay.Loop ?? state.Loops,
                };
            }).ToArray(),
            Actions = entry.Actions.Select(action =>
            {
                if (action.FramesPerSecond is null && action.Loops is null)
                {
                    return action;
                }

                SpriteAuthoredActionTiming? timing = overlay.ActionTimings?.SingleOrDefault(value => StringComparer.Ordinal.Equals(value.Name, action.Name));
                return action with
                {
                    FramesPerSecond = timing?.FramesPerSecond ?? overlay.FramesPerSecond ?? action.FramesPerSecond,
                    Loops = timing?.Loop ?? overlay.Loop ?? action.Loops,
                    FrameIndices = overlay.Sequence ?? action.FrameIndices,
                };
            }).ToArray(),
        };
    }
}

/// <summary>
/// Strict JSON and safe filesystem operations for authored sprite overlays.
/// The authoring root is separate from the generated publication root: a later
/// regeneration consumes a validated overlay as import input rather than
/// placing it in a publication.
/// </summary>
public static class SpriteAuthoredOverlayStore
{
    private const int MaximumOverlayBytes = 1024 * 1024;
    private static readonly JsonSerializerOptions Json = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
        NumberHandling = JsonNumberHandling.Strict,
        UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
    };

    public static SpriteAuthoredOverlayDocument Read(ReadOnlySpan<byte> bytes)
    {
        if (bytes.IsEmpty || bytes.Length > MaximumOverlayBytes)
        {
            throw new FormatException("A sprite overlay document is empty or exceeds its byte quota.");
        }

        try
        {
            return JsonSerializer.Deserialize<SpriteAuthoredOverlayDocument>(bytes, Json)
                ?? throw new FormatException("The sprite overlay document is empty.");
        }
        catch (JsonException exception)
        {
            throw new FormatException("The sprite overlay document is not a supported strict JSON document.", exception);
        }
    }

    public static void Validate(SpriteAuthoredOverlayDocument document, SpriteInspectionCatalog catalog, SpriteContentDigest authoringBasisDigest)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentNullException.ThrowIfNull(catalog);
        if (document.SchemaVersion != SpriteAuthoredOverlayDocument.CurrentSchemaVersion)
        {
            throw new FormatException("The sprite overlay schema version is not supported.");
        }

        document.AuthoringBasisDigest.Validate();
        if (document.AuthoringBasisDigest != authoringBasisDigest)
        {
            throw new FormatException("The sprite overlay was authored against a different structural authoring basis.");
        }

        ArgumentNullException.ThrowIfNull(document.Overlays);
        HashSet<string> ids = new(StringComparer.Ordinal);
        foreach (SpriteAuthoredOverlay overlay in document.Overlays)
        {
            ArgumentNullException.ThrowIfNull(overlay);
            SpriteLogicalNames.RequireId(overlay.Id, nameof(overlay.Id));
            if (!ids.Add(overlay.Id))
            {
                throw new FormatException($"The sprite overlay contains duplicate ID '{overlay.Id}'.");
            }

            SpriteInspectionEntry entry = catalog.Require(overlay.Id);
            if (entry.Kind == SpriteInspectionKind.ClassicWeapon
                && (overlay.FramesPerSecond is not null || overlay.Loop is not null || overlay.Sequence is not null))
            {
                throw new FormatException("Weapon timing and sequence are action-specific and cannot be authored as resource-wide values.");
            }
            ValidateValues(overlay, entry);
        }
    }

    public static string ResolveRelativePath(string rootDirectory, string relativePath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(rootDirectory);
        SpriteLogicalNames.RequirePath(relativePath, nameof(relativePath));
        string root = Path.GetFullPath(rootDirectory);
        string candidate = Path.GetFullPath(Path.Combine(root, relativePath.Replace('/', Path.DirectorySeparatorChar)));
        string prefix = root.EndsWith(Path.DirectorySeparatorChar) ? root : root + Path.DirectorySeparatorChar;
        if (!candidate.StartsWith(prefix, StringComparison.Ordinal))
        {
            throw new ArgumentException("The overlay path escaped the publication directory.", nameof(relativePath));
        }

        return candidate;
    }

    /// <summary>
    /// Proves that authored source files cannot reside in or contain the exact
    /// generated publication tree. This check is lexical over normalized
    /// absolute paths so it also works when discard is deliberately invoked
    /// without opening a publication directory.
    /// </summary>
    public static void ValidateRootSeparation(string publicationDirectory, string authoringDirectory)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(publicationDirectory);
        ArgumentException.ThrowIfNullOrWhiteSpace(authoringDirectory);
        string publication = TrimTrailingSeparator(Path.GetFullPath(publicationDirectory));
        string authoring = TrimTrailingSeparator(Path.GetFullPath(authoringDirectory));
        if (StringComparer.Ordinal.Equals(publication, authoring)
            || IsNestedWithin(publication, authoring)
            || IsNestedWithin(authoring, publication))
        {
            throw new ArgumentException("The authored sprite source root must be distinct from, and neither contain nor be contained by, the generated publication root.");
        }
    }

    /// <summary>Overlay files are JSON leaves relative to a separately selected authored source root.</summary>
    public static void ValidateOverlayRelativePath(string relativePath)
    {
        SpriteLogicalNames.RequirePath(relativePath, nameof(relativePath));
        if (!relativePath.StartsWith("sprites/", StringComparison.Ordinal)
            || !relativePath.EndsWith(".json", StringComparison.Ordinal))
        {
            throw new ArgumentException("A sprite overlay must be a relative JSON sidecar under sprites/ in the authored source root.", nameof(relativePath));
        }
    }

    public static void Write(string publicationDirectory, string authoringDirectory, string relativePath, SpriteAuthoredOverlayDocument document, SpriteInspectionCatalog catalog, SpriteContentDigest authoringBasisDigest)
    {
        Validate(document, catalog, authoringBasisDigest);
        ValidateRootSeparation(publicationDirectory, authoringDirectory);
        ValidateOverlayRelativePath(relativePath);
        string target = ResolveRelativePath(authoringDirectory, relativePath);
        string? directory = Path.GetDirectoryName(target);
        if (string.IsNullOrEmpty(directory))
        {
            throw new IOException("The overlay target has no parent directory.");
        }

        Directory.CreateDirectory(directory);
        byte[] bytes = [.. JsonSerializer.SerializeToUtf8Bytes(document, Json), (byte)'\n'];
        if (bytes.Length > MaximumOverlayBytes)
        {
            throw new FormatException("The serialized sprite overlay exceeds its byte quota.");
        }
        string temporary = Path.Combine(directory, $".{Path.GetFileName(target)}.{Guid.NewGuid():N}.tmp");
        string backup = target + ".bak";
        try
        {
            using (FileStream stream = new(temporary, FileMode.CreateNew, FileAccess.Write, FileShare.None, 4096, FileOptions.WriteThrough))
            {
                stream.Write(bytes);
                stream.Flush(flushToDisk: true);
            }

            if (File.Exists(target))
            {
                if (File.Exists(backup))
                {
                    throw new IOException("The sprite overlay recovery path already exists; inspect or move it before replacing the overlay.");
                }

                File.Replace(temporary, target, backup, ignoreMetadataErrors: true);
            }
            else
            {
                File.Move(temporary, target);
            }
        }
        finally
        {
            if (File.Exists(temporary))
            {
                File.Delete(temporary);
            }
        }
    }

    /// <summary>Moves an overlay out of the separate authored root without reading or changing any publication.</summary>
    public static bool Discard(string publicationDirectory, string authoringDirectory, string relativePath)
    {
        ValidateRootSeparation(publicationDirectory, authoringDirectory);
        ValidateOverlayRelativePath(relativePath);
        string target = ResolveRelativePath(authoringDirectory, relativePath);
        if (!File.Exists(target))
        {
            return false;
        }

        string discarded = target + ".discarded";
        if (File.Exists(discarded))
        {
            throw new IOException("The sprite overlay recovery path already exists; inspect or move it before discarding again.");
        }

        File.Move(target, discarded);
        return true;
    }

    private static string TrimTrailingSeparator(string path)
    {
        string root = Path.GetPathRoot(path) ?? string.Empty;
        return path.Length == root.Length ? path : path.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
    }

    private static bool IsNestedWithin(string candidate, string root)
    {
        string prefix = root.EndsWith(Path.DirectorySeparatorChar) ? root : root + Path.DirectorySeparatorChar;
        return candidate.StartsWith(prefix, StringComparison.Ordinal);
    }

    internal static void ValidateValues(SpriteAuthoredOverlay overlay, SpriteInspectionEntry entry)
    {
        if (overlay.DisplayName is not null && (string.IsNullOrWhiteSpace(overlay.DisplayName) || overlay.DisplayName.Any(char.IsControl)))
        {
            throw new FormatException("A sprite overlay display name must be non-empty plain text.");
        }

        overlay.Pivot?.Validate(nameof(overlay.Pivot));
        overlay.DisplaySize?.Validate(nameof(overlay.DisplaySize));
        if (overlay.DisplaySize is { X: <= 0F } or { Y: <= 0F }
            || overlay.FramesPerSecond is <= 0F
            || (overlay.FramesPerSecond is not null && !float.IsFinite(overlay.FramesPerSecond.Value))
            || overlay.Sequence is { Count: 0 }
            || overlay.Sequence?.Any(index => index < 0 || index >= entry.Frames.Count) == true)
        {
            throw new FormatException("A sprite overlay contains invalid authored presentation values.");
        }

        ValidateFrameRects(overlay.FrameRects, entry);
        ValidateTimings(overlay.StateTimings, entry.States.Select(state => state.Name), nameof(overlay.StateTimings));
        ValidateTimings(overlay.ActionTimings,
            entry.Actions.Where(action => action.FramesPerSecond is not null || action.Loops is not null).Select(action => action.Name),
            nameof(overlay.ActionTimings));
    }

    private static void ValidateFrameRects(IReadOnlyList<SpriteAuthoredFrameRect>? rectangles, SpriteInspectionEntry entry)
    {
        if (rectangles is null) return;
        HashSet<int> frames = [];
        foreach (SpriteAuthoredFrameRect rect in rectangles)
        {
            ArgumentNullException.ThrowIfNull(rect);
            if (rect.FrameIndex < 0 || rect.X < 0 || rect.Y < 0 || rect.Width <= 0 || rect.Height <= 0
                || !frames.Add(rect.FrameIndex) || !entry.Frames.Any(frame => frame.FrameIndex == rect.FrameIndex)
                || rect.X > entry.Atlas.Width - rect.Width || rect.Y > entry.Atlas.Height - rect.Height)
            {
                throw new FormatException("A sprite overlay frame rectangle must uniquely identify a generated frame and remain inside its atlas.");
            }
        }
    }

    private static void ValidateTimings<TTiming>(IReadOnlyList<TTiming>? timings, IEnumerable<string> availableNames, string parameterName)
        where TTiming : class
    {
        if (timings is null) return;
        HashSet<string> available = availableNames.ToHashSet(StringComparer.Ordinal);
        HashSet<string> names = new(StringComparer.Ordinal);
        foreach (TTiming timing in timings)
        {
            ArgumentNullException.ThrowIfNull(timing);
            string name = timing switch
            {
                SpriteAuthoredStateTiming state => state.Name,
                SpriteAuthoredActionTiming action => action.Name,
                _ => throw new InvalidOperationException("Unknown sprite timing type."),
            };
            float? framesPerSecond = timing switch
            {
                SpriteAuthoredStateTiming state => state.FramesPerSecond,
                SpriteAuthoredActionTiming action => action.FramesPerSecond,
                _ => null,
            };
            bool? loop = timing switch
            {
                SpriteAuthoredStateTiming state => state.Loop,
                SpriteAuthoredActionTiming action => action.Loop,
                _ => null,
            };
            if (string.IsNullOrWhiteSpace(name) || name.Any(char.IsControl) || !available.Contains(name) || !names.Add(name)
                || (framesPerSecond is null && loop is null) || framesPerSecond is <= 0F || (framesPerSecond is not null && !float.IsFinite(framesPerSecond.Value)))
            {
                throw new FormatException($"The sprite overlay has an invalid {parameterName} value.");
            }
        }
    }
}
