import {
  append,
  engineCapability,
  gameplayDefinition,
  inputAction,
  kernelCapability,
  observePairs,
  productIntent,
  schedule,
  Standard,
  system,
} from '@rusty-engine/runtime-composition-authoring';

// Product Layout declares the closed inputs, capabilities, and cadence. Rust
// remains the only Dagger gameplay evaluator and mutation authority; this
// source is build-time data, never an input listener, timer, or callback.
export default {
  product: 'rusty.product.dagger',
  capabilities: [
    kernelCapability('dagger.move', 'dagger-move'),
    kernelCapability('dagger.look', 'dagger-look'),
    kernelCapability('dagger.attack', 'dagger-attack'),
    kernelCapability('dagger.session', 'dagger-session'),
    kernelCapability('dagger.content', 'dagger-content'),
    kernelCapability('dagger.equipment', 'dagger-equipment'),
    kernelCapability('dagger.inventory', 'dagger-inventory'),
    kernelCapability('dagger.loot', 'dagger-loot'),
    kernelCapability('dagger.settings', 'dagger-settings'),
    kernelCapability('dagger.debug', 'dagger-debug'),
    kernelCapability('dagger.simulation', 'dagger-simulation'),
    kernelCapability('dagger.simulation-result', 'dagger-simulation-result'),
    engineCapability('dagger.observe-pairs', 'runtime.observe-pairs'),
    kernelCapability('dagger.observe-pairs-result', 'dagger-observe-pairs-result'),
  ],
  intentDescriptors: [
    productIntent({ id: 'dagger.move.forward', valueKind: 'digital', capability: 'dagger.move', payload: { direction: 'forward' } }),
    productIntent({ id: 'dagger.move.backward', valueKind: 'digital', capability: 'dagger.move', payload: { direction: 'backward' } }),
    productIntent({ id: 'dagger.move.left', valueKind: 'digital', capability: 'dagger.move', payload: { direction: 'left' } }),
    productIntent({ id: 'dagger.move.right', valueKind: 'digital', capability: 'dagger.move', payload: { direction: 'right' } }),
    productIntent({ id: 'dagger.look.yaw', valueKind: 'axis', capability: 'dagger.look', payload: { axis: 'yaw' } }),
    productIntent({ id: 'dagger.look.pitch', valueKind: 'axis', capability: 'dagger.look', payload: { axis: 'pitch' } }),
    productIntent({ id: 'dagger.attack', valueKind: 'digital', capability: 'dagger.attack', payload: { action: 'attack' } }),
    productIntent({ id: 'dagger.session.reset', valueKind: 'digital', capability: 'dagger.session', payload: { action: 'reset' } }),
    productIntent({ id: 'dagger.loot.open', valueKind: 'digital', capability: 'dagger.loot', payload: { action: 'open' } }),
    productIntent({ id: 'dagger.loot.close', valueKind: 'digital', capability: 'dagger.loot', payload: { action: 'close' } }),
    productIntent({ id: 'dagger.debug.nav', valueKind: 'digital', capability: 'dagger.debug', payload: { action: 'toggle-nav-debug' } }),
    // Direct payload values carry the user-selected data at claim time. Empty
    // capability metadata deliberately avoids turning a descriptor default
    // into a settings, inventory, equipment, loot, or content command.
    productIntent({ id: 'dagger.content.jump', valueKind: 'product-payload', payloadContract: 'dagger.content.jump.v1', capability: 'dagger.content', payload: {} }),
    productIntent({ id: 'dagger.equipment.equip', valueKind: 'product-payload', payloadContract: 'dagger.equipment.equip.v1', capability: 'dagger.equipment', payload: {} }),
    productIntent({ id: 'dagger.equipment.unequip', valueKind: 'product-payload', payloadContract: 'dagger.equipment.unequip.v1', capability: 'dagger.equipment', payload: {} }),
    productIntent({ id: 'dagger.inventory.move', valueKind: 'product-payload', payloadContract: 'dagger.inventory.move.v1', capability: 'dagger.inventory', payload: {} }),
    productIntent({ id: 'dagger.loot.transfer-stack', valueKind: 'product-payload', payloadContract: 'dagger.loot.transfer-stack.v1', capability: 'dagger.loot', payload: {} }),
    productIntent({ id: 'dagger.loot.transfer-item', valueKind: 'product-payload', payloadContract: 'dagger.loot.transfer-item.v1', capability: 'dagger.loot', payload: {} }),
    productIntent({ id: 'dagger.settings.update', valueKind: 'product-payload', payloadContract: 'dagger.settings.update.v1', capability: 'dagger.settings', payload: {} }),
  ],
  inputMap: [
    inputAction({ id: 'dagger.move.forward.w', intent: 'dagger.move.forward', trigger: { kind: 'key', code: 'key-w', edge: 'held', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.move.backward.s', intent: 'dagger.move.backward', trigger: { kind: 'key', code: 'key-s', edge: 'held', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.move.left.a', intent: 'dagger.move.left', trigger: { kind: 'key', code: 'key-a', edge: 'held', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.move.right.d', intent: 'dagger.move.right', trigger: { kind: 'key', code: 'key-d', edge: 'held', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.move.forward.controller', intent: 'dagger.move.forward', trigger: { kind: 'controller-button', button: 'button-12', edge: 'held', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.move.backward.controller', intent: 'dagger.move.backward', trigger: { kind: 'controller-button', button: 'button-13', edge: 'held', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.move.left.controller', intent: 'dagger.move.left', trigger: { kind: 'controller-button', button: 'button-14', edge: 'held', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.move.right.controller', intent: 'dagger.move.right', trigger: { kind: 'controller-button', button: 'button-15', edge: 'held', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.look.yaw.pointer', intent: 'dagger.look.yaw', trigger: { kind: 'pointer-axis', axis: 'x', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.look.pitch.pointer', intent: 'dagger.look.pitch', trigger: { kind: 'pointer-axis', axis: 'y', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.look.yaw.controller', intent: 'dagger.look.yaw', trigger: { kind: 'controller-axis', axis: 'axis-2', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.look.pitch.controller', intent: 'dagger.look.pitch', trigger: { kind: 'controller-axis', axis: 'axis-3', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.attack.space', intent: 'dagger.attack', trigger: { kind: 'key', code: 'space', edge: 'pressed', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.attack.pointer', intent: 'dagger.attack', trigger: { kind: 'pointer-button', button: 'primary', edge: 'pressed', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.attack.controller', intent: 'dagger.attack', trigger: { kind: 'controller-button', button: 'button-0', edge: 'pressed', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.session.reset.r', intent: 'dagger.session.reset', trigger: { kind: 'key', code: 'key-r', edge: 'pressed', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.loot.open.e', intent: 'dagger.loot.open', trigger: { kind: 'key', code: 'key-e', edge: 'pressed', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.loot.close.g', intent: 'dagger.loot.close', trigger: { kind: 'key', code: 'key-g', edge: 'pressed', context: 'gameplay.default' } }),
    inputAction({ id: 'dagger.debug.nav.n', intent: 'dagger.debug.nav', trigger: { kind: 'key', code: 'key-n', edge: 'pressed', context: 'gameplay.default' } }),
  ],
  schedule: schedule({
    simulation: append(
      Standard.simulation,
      observePairs({
        id: 'dagger.observe-pairs',
        engineBinding: engineCapability('dagger.observe-pairs', 'runtime.observe-pairs'),
        operationBinding: kernelCapability('dagger.observe-pairs-result', 'dagger-observe-pairs-result'),
        observerRole: 'dagger.player-observer',
        targetRole: 'dagger.combat-target',
        quotas: { observers: 1, targets: 64, pairs: 64, aggregates: 64 },
        cadence: 1,
      }),
      system('dagger.simulation', {
        capability: 'dagger.simulation',
        after: ['dagger.observe-pairs'],
        definition: 'dagger.gameplay',
        reads: ['dagger.session'],
        writes: ['dagger.session'],
        payload: {
          kind: 'dagger.simulation.v1',
          operationBinding: 'dagger.simulation-result',
          operationType: 'dagger.simulation.result.v1',
        },
      }),
    ),
  }),
  gameplayDefinitions: [gameplayDefinition('dagger.gameplay', {
    kind: 'dagger.gameplay.v1',
    gameplayPackage: 'content/runtime/dagger-core.package.json',
    encounterDefinitions: 'content/runtime/privateers-hold.encounters.json',
    project: 'content/projects/privateers-hold.project.json',
    navigation: 'content/projects/privateers-hold.navgrid.json',
  })],
};
