/** Product-local presentation only. The Engine application host owns the canvas and viewport. */
export const daggerProductUiStyles = `
:host, .dagger-product-ui { color: #f2eadc; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
* { box-sizing: border-box; } button { font: inherit; }
.dagger-product-ui { height: 100%; inset: 0; overflow: hidden; position: absolute; }
.dagger-game-stage { inset: 0; pointer-events: none; position: absolute; }
.dagger-title { background: rgba(9,13,15,.84); border: 1px solid rgba(199,169,106,.52); color: #f0d879; font: 600 clamp(.8rem,2vw,1rem) Georgia,serif; left: 18px; padding: 8px 14px; position: absolute; top: 18px; }
.dagger-encounter { background: rgba(14,22,21,.88); border-left: 2px solid #8de0b1; color: #cde3d9; display: grid; gap: 2px; max-width: min(440px,60vw); padding: 8px 11px; position: absolute; right: 18px; top: 18px; }
.dagger-encounter strong { color: #f0d879; font-size: .78rem; }.dagger-encounter span { font-size: .7rem; }
.dagger-hud { bottom: 12px; display: grid; gap: 8px; grid-template-columns: minmax(230px,440px) minmax(160px,220px); left: 50%; max-width: calc(100% - 20px); pointer-events: none; position: absolute; transform: translateX(-50%); width: min(94vw,700px); }
.dagger-meters { background: rgba(9,13,15,.9); border: 5px solid #302a20; box-shadow: inset 0 0 0 1px #9d8959; display: grid; gap: 4px; padding: 7px; }
.dagger-meter { align-items: center; display: grid; gap: 7px; grid-template-columns: 68px 1fr 70px; }.dagger-meter label { color: #d8c58b; font-size: .62rem; font-weight: 800; letter-spacing: .08em; text-transform: uppercase; }.dagger-meter strong { font: 600 .67rem ui-monospace,monospace; text-align: right; }
.dagger-meter-track { background: #151a19; border: 1px solid #4b4431; height: 12px; overflow: hidden; }.dagger-meter-fill { display:block; height:100%; }.health { background:#bb4a3d; }.stamina { background:#8eab47; }.magicka { background:#577eb4; }
.dagger-progression { background: rgba(9,13,15,.9); border: 1px solid rgba(199,169,106,.55); display:grid; gap:3px; grid-template-columns:1fr 1fr; padding:8px; }.dagger-progression span { color:#c7a96a; font-size:.57rem; font-weight:800; letter-spacing:.06em; text-transform:uppercase; }.dagger-progression strong { font:600 .72rem ui-monospace,monospace; }
.dagger-corner-actions { display:flex; gap:7px; pointer-events:auto; position:absolute; right:18px; bottom:18px; }.dagger-product-ui button { background:#202827; border:1px solid #665b3e; border-radius:5px; color:#f2e4c0; cursor:pointer; font-weight:700; padding:7px 10px; }.dagger-product-ui button:hover,.dagger-product-ui button:focus-visible { border-color:#f0d879; outline:2px solid transparent; }.dagger-product-ui button:disabled { cursor:default; opacity:.55; }
.dagger-notices { bottom:104px; display:grid; gap:6px; left:50%; max-width:min(600px,calc(100% - 24px)); pointer-events:none; position:absolute; transform:translateX(-50%); }.dagger-notice { background:rgba(19,26,25,.94); border:1px solid #7d946a; color:#e5eed4; margin:0; padding:7px 13px; text-align:center; }.dagger-notice.warning { border-color:#c47362; color:#ffd0c9; }.dagger-notice.success { border-color:#92cc8f; }
.dagger-layer { align-items:center; background:rgba(3,6,7,.76); display:grid; inset:0; justify-items:center; padding:14px; position:absolute; z-index:4; }.dagger-dialog { background:#111617; border:8px solid #302a20; box-shadow:0 28px 90px rgba(0,0,0,.7),inset 0 0 0 1px #9d8959; max-height:100%; max-width:1200px; overflow:auto; padding:16px; width:min(100%,1200px); }.dagger-dialog.small { max-width:560px; }.dagger-dialog header { align-items:start; border-bottom:1px solid #5d5439; display:flex; gap:18px; justify-content:space-between; margin-bottom:12px; padding-bottom:10px; }.dagger-dialog h1,.dagger-dialog h2,.dagger-dialog h3,.dagger-dialog p { margin:0; }.dagger-dialog h2 { color:#f0d879; font:500 1.65rem Georgia,serif; }.dagger-kicker { color:#c7a96a; font-size:.64rem; font-weight:800; letter-spacing:.1em; text-transform:uppercase; }.dagger-help { color:#b7c3bd; font-size:.82rem; line-height:1.45; margin:0 0 12px; }
.dagger-menu-actions { display:grid; gap:8px; }.dagger-menu-actions button { align-items:baseline; display:flex; justify-content:space-between; text-align:left; }.dagger-menu-actions small { color:#c7a96a; font:600 .7rem ui-monospace,monospace; }.dagger-control-list { color:#b7c3bd; display:grid; gap:6px; grid-template-columns:repeat(2,1fr); margin-top:16px; }.dagger-control-list div { border-top:1px solid #343d3a; display:flex; justify-content:space-between; padding-top:6px; }
.dagger-capacity { display:flex; gap:7px; margin-bottom:12px; overflow:auto; }.dagger-capacity div { background:#0d1314; border:1px solid #334142; display:grid; gap:2px; min-width:130px; padding:7px 9px; }.dagger-capacity span,.dagger-receipt span { color:#c7a96a; font-size:.61rem; font-weight:800; letter-spacing:.08em; text-transform:uppercase; }.dagger-capacity strong { font:600 .78rem ui-monospace,monospace; }
.dagger-inventory-layout { display:grid; gap:12px; grid-template-columns:minmax(220px,.85fr) minmax(430px,1.5fr) minmax(210px,.75fr); }.dagger-panel { background:rgba(9,13,14,.85); border:1px solid #665b3e; min-width:0; padding:10px; }.dagger-panel h3 { color:#eddfb7; font-size:.9rem; margin:3px 0 8px; }.dagger-equipment { display:grid; gap:7px; grid-template-columns:repeat(2,minmax(0,1fr)); }.dagger-equipment-slot { background:#151a19; border:1px solid #4c4936; min-height:82px; padding:7px; }.dagger-equipment-slot p { color:#9baaa4; font:.6rem ui-monospace,monospace; text-transform:uppercase; }.dagger-equipment-slot button { margin-top:7px; overflow:hidden; text-align:left; text-overflow:ellipsis; white-space:nowrap; width:100%; }.dagger-equipment-slot .empty { color:#82908a; font:italic .74rem Georgia,serif; display:block; margin-top:10px; }.dagger-equipment-slot .ready { border-color:#d6b766; }
.dagger-grid { display:grid; gap:5px; grid-template-columns:repeat(10,minmax(36px,1fr)); max-height:440px; overflow:auto; }.dagger-grid button { aspect-ratio:1; font-size:.57rem; min-width:0; overflow:hidden; padding:4px; text-overflow:ellipsis; white-space:nowrap; }.dagger-grid button.selected { border-color:#f0d879; box-shadow:inset 0 0 0 1px #f0d879; }.dagger-detail { color:#c3d0cb; font-size:.82rem; line-height:1.45; }.dagger-detail dl { display:grid; gap:7px; margin:12px 0; }.dagger-detail dl div { border-bottom:1px solid #273536; display:flex; justify-content:space-between; padding-bottom:5px; }.dagger-detail dt { color:#c7a96a; font-size:.66rem; text-transform:uppercase; }.dagger-detail dd { margin:0; text-align:right; }.dagger-receipt { background:#241f14; border:1px solid #827146; margin-top:12px; padding:7px 9px; }.dagger-receipt.rejected { border-color:#a35a50; color:#ffd0c9; }
.dagger-loot-list { display:grid; gap:7px; }.dagger-loot-list button { align-items:baseline; display:flex; justify-content:space-between; text-align:left; width:100%; }.dagger-loot-list strong { color:#f0d879; font-size:.74rem; }.dagger-character-summary { background:#0d1314; border:1px solid #334142; display:grid; gap:1px; grid-template-columns:repeat(3,1fr); margin-bottom:12px; }.dagger-character-summary div { background:#111817; display:grid; gap:3px; padding:9px; }.dagger-character-summary span,.dagger-stat-list dt { color:#c7a96a; font-size:.62rem; font-weight:800; letter-spacing:.08em; text-transform:uppercase; }.dagger-character-columns { display:grid; gap:12px; grid-template-columns:repeat(3,minmax(0,1fr)); }.dagger-stat-list { display:grid; gap:6px; margin:0; }.dagger-stat-list div { border-bottom:1px solid #273536; display:flex; justify-content:space-between; padding-bottom:5px; }.dagger-stat-list dd { font:600 .78rem ui-monospace,monospace; margin:0; }
@media (max-width:820px) { .dagger-hud { grid-template-columns:1fr; max-width:calc(100% - 12px); width:min(96vw,540px); }.dagger-progression { display:none; }.dagger-inventory-layout { grid-template-columns:1fr 1fr; }.dagger-detail { grid-column:1/-1; }.dagger-character-columns { grid-template-columns:1fr 1fr; }.dagger-character-columns .skills { grid-column:1/-1; } }
@media (max-width:520px) { .dagger-title { left:8px; top:8px; }.dagger-encounter { display:none; }.dagger-corner-actions { bottom:8px; right:8px; }.dagger-corner-actions button:not(:first-child) { display:none; }.dagger-meter { grid-template-columns:58px 1fr 58px; }.dagger-inventory-layout,.dagger-character-columns { grid-template-columns:1fr; }.dagger-detail,.dagger-character-columns .skills { grid-column:auto; }.dagger-dialog { border-width:5px; padding:10px; }.dagger-grid { grid-template-columns:repeat(5,minmax(40px,1fr)); } }
`;
